### ISSUE TITLE
Can't mass delete Labels

### ISSUE THREAD

**Issue by lhviet** [LuatixHQ/opencti#4460] opened 2023-09-26 21:20 UTC
## Description

Settings > Taxonomy > Labels.

I try to select multiple labels and mass delete them.
No errors and the job is Complete in the Background Task page.

However, they are still there.

## Environment

demo.opencti.io

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by SamuelHassine** [comment] 2023-10-08 15:57
Duplicate of #4504.

**Closed as completed by SamuelHassine** 2023-10-08 15:57 UTC
Labels: bug, duplicate
