### ISSUE TITLE
Relationships break negative filtering in a stream

### ISSUE THREAD

**Issue by ristowee** [LuatixHQ/opencti#3776] opened 2023-07-14 10:15 UTC
## Description

The relationships seem to output objects in the stream even if they should be filtered out by a negative filter.

I assume it goes like this: the stream encounters an entity / observable which is allowed through by the filter, it is processed for relationships and the related objects are retrieved from the database and written in the stream without checking them against the filter.

## Environment

1. OS (where OpenCTI server runs): A docker image on Debian 10
2. OpenCTI version: 5.9.2 (also present in 5.8, 5,7 and older)
3. OpenCTI client: frontend (also streamed using a browser)
4. Other environment details:

## Reproducible Steps

1. (Create an author _AuthorX_ or use an existing one)
2. Create a stream where _AuthorX_ is filtered out (NOT: Author _AuthorX_)
3. Create an observable with _AuthorX_ as the author
4. Create another thingy e.g. an indicator, which has another author or no author at all
5. Create a relationship between those two
6. Stream the data out (e.g. with a browser)

## Expected Output

The observable with the _AuthorX_ should not found be in the stream.
Also if the relationship has also _AuthorX_ as the author it should be missing, too.

## Actual Output

The observable with _AuthorX_ is written in the stream.

## Additional information

If both objects (3. & 4.) have _AuthorX_ as the author, neither is seen in the stream. If there is no relationship between them, the _AuthorX_ observable is not seen in the stream.

Also if there is a relationship by _AuthorX_ that links two objects, which are not authored by _AuthorX_, the relationship object is written in the stream. I'd expect it to be left out of the stream.

**Comment by richard-julien** [comment] 2023-07-14 22:35
Ok so 2 things of this one for me.

1. There is a bug in the NOT filter for instances (like createdBy) that prevent the cache to correctly built the resolution filters. So the not filter is not working in the stream as we compare stixId with the internal id. Not sure how you make it work in your use case because on my side the step3 is publishing the observable in the stream.

**There is not doubt that we need to fix this.**

2. Publication of the element that are part of a relation. This is actually by design. To provide stream data consistency every references are published independently of the filters (except for data segregation). Its true for all references like created_by_ref of an indicator, object_refs of a report, etc. 

On this one its a decision that can be challenged. Relationships are a bit different by their design and maybe should be published in the stream only if both side of the relation fully pass the filtering. Any opinion on that @SamuelHassine ? @Jipegien ?

**Comment by richard-julien** [comment] 2023-07-15 17:14
Branch issue/3776 open with the point 1

**Comment by SamuelHassine** [comment] 2023-07-17 23:23
Hello @ristowee,

Thanks @richard-julien for the fix, it will be included in the next release (PR merged). 

For the other behaviour, I've created the page https://docs.opencti.io/latest/usage/feeds/ to explain properly what to expect.

In your case, I think the best solution is to consume the stream with `no-dependencies=true`, which will solve your problem.

You can easily test in your browser by putting `no-dependencies=true` as a parameter of the URL: https://opencti/streams/ID?no-dependencies=true.

The env var `CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true` is available in all stream connectors.

Kind regards,
Samuel

**Closed as completed by SamuelHassine** 2023-07-17 23:23 UTC
Labels: bug, solved
