### ISSUE TITLE
Malwaretype dropdown no autoclosing

### ISSUE THREAD

**Issue by Chasbrot** [LuatixHQ/opencti#3023] opened 2023-03-16 10:13 UTC
## Description

When adding a new malware the the dropdown for the malwaretype doens't close automatically.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.1 LTS
2. OpenCTI version: 5.6.1
3. OpenCTI client: frontent
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Knowledge -> Arsenal -> + -> Malware types

## Expected Output

Dropdown closes after selection

## Actual Output

Dropdown doesn't close

**Comment by richard-julien** [comment] 2023-03-23 22:59
Hi, can you try to reproduce in the demo, on my side it looks like to work as expected.

**Comment by Chasbrot** [comment] 2023-03-24 19:46
here:
![image](https://user-images.githubusercontent.com/58513998/227624004-c1263a5f-cf07-4277-9f53-0a3566196daa.png)
BUT
i am so sorry, i just noticed that the malware type attribute in a malware sample is a multi selection. i always thought that there was only one category allowed since it looked identical to all other selections and dropdowns. therefore i wondered why it wasn't closing like the others after selecting an entry.

**Comment by richard-julien** [comment] 2023-03-25 00:40
Hi @Chasbrot , thanks for the feedback.
Yes malware types are multiple according to STIX

![image](https://user-images.githubusercontent.com/285555/227668552-0dcb6822-8cda-4cdf-b538-94e4de2c4428.png)

Closing the issue :)

**Closed as completed by richard-julien** 2023-03-25 00:40 UTC
Labels: question, solved
