### ISSUE TITLE
Trigger Notifications via email are not working

### ISSUE THREAD

**Issue by nhuber0724** [LuatixHQ/opencti#8824] opened 2024-10-29 15:59 UTC
## Environment

 OpenCTI version: 6.3.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Simple Mailer Notifier 
2. Create an alert based on the notifier developed in the first step
3. In the alert, filter on Group (for the group to whom you wish to send the notifications) as well as other filter parameters (labels, event scope, etc)
4. Apply the filters described in step 3 to an entity in the platform. The group members should all receive an email notification; however, this doesn't occur. 

## Expected Output

Group members should receive an email notification. 

## Actual Output

Group members don't receive an email notification.

**Comment by nino-filigran** [comment] 2024-10-31 09:05
Do you have some details (config) of the mailer you created? Given that we receive evrything well with the default platform mailer, I guess the issue is located in the mailer.

**Comment by SamuelHassine** [comment] 2024-12-23 15:40
@nhuber0724 @nino-filigran @RomainGUIGNARD  any news or closing?

**Comment by nhuber0724** [comment] 2024-12-23 15:48
hey @SamuelHassine apologies, we can close this. It wasn't a technical issue. I worked with the client to identify and fix the issue.

**Closed as completed** 2024-12-23 15:48 UTC
Labels: question, solved
