### ISSUE TITLE
Enrich entity on graph view

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#2158] opened 2022-06-14 18:01 UTC
## Use case

I would like to have the enrichment list panel available through a enrichment button on the Graph panel. This would allow me to easily enrich and expand from an existing observable without exiting the graph view.

## Current Workaround

Open each observable using the the following button in order to then use the normal enrichment feature in each observable.
![image](https://user-images.githubusercontent.com/4184292/173657581-e893fb9a-1c1f-4bfd-aedf-a7000c08ab10.png)

## Proposed Solution

An enrichment button that would be available as soon as I selected an entity like an observable on the graph panel.

## Additional Information

![image](https://user-images.githubusercontent.com/4184292/173658089-138e942e-764f-43b2-ac42-f4fb8fed06a0.png)

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment] 2022-09-29 11:45
Duplicate of #2072.

**Closed as completed by SamuelHassine** 2022-09-29 11:45 UTC
Labels: duplicate, feature
