### ISSUE TITLE
[CSV Mapper] MISSING REFERENCE ERROR when importing file with CSV mapper

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6818] opened 2024-04-25 18:55 UTC
## Description

I ran the test on two different platforms with exactly **the same file and the same CSV mapper configuration**:
- On one platform, import works
- On the other, I get a “MISSING REFERENCE ERROR”.

Since the CSV does not contain an entity ID, but the platform create all object, I don't understand how we can get a “MISSING REFERENCE ERROR”. What's more, why only on one platform and not the other?

## Environment

OCTI 6.0.10

## Reproducible Steps

- On the "demo" platform, you can find the CSV mapper "Test bug missing ref error" with the configuration.
- The file used for the test is this one : 

[Test.csv](https://github.com/OpenCTI-Platform/opencti/files/15119419/Test.csv)

The demo platform is the that's the one it works on. So that I can show you the second platform on which it doesn't work, please ping me.

nb: 
- I know, it's not a repro case sorry. I've been working on this bug for 2 hours and I've tried everything... I can't get any logic out of this problem
- I also tried to find more data on the error logs but nothing (neither through the browser network nor in the platform logs).

## Screenshots

![Screenshot 2024-04-25 204417](https://github.com/OpenCTI-Platform/opencti/assets/70956706/3bf6d225-53a5-42d4-9dcd-4ac55afb4baa)

**Comment by nino-filigran** [comment] 2024-04-26 08:01
I also have a weird behavior on demo (public) & testing, since I bump on the exact same error as you do. However it seems that entities are created in the platform since I can find them except for the TOOL "connectWise" that is not created (but added as alias of screenConnect).
However it seems that some intrusion sets are not found (the ones corresponding to Group-IB: Fat Cats, HHS: Royal & BlackCat Ransomware: The Threat to the Health Sector, Interal (TIN) & KASP)) & therefore, no relation can be created between tools & these intrusions sets. If you look at the relation with the tools for the corresponding lines of your CSV you'll see that the relation does not exist in the platform. 

Could that be the root cause of the issue? Trying to create a relation between 2 entities, with one not existing in the platform?

**Comment by Lhorus6** [comment] 2024-04-26 08:53
"MISSING REFERENCE ERROR" occurs when an entity is not found and is required (for a relationship, for example).

E.g. this happens when the data source refers to an entity with an ID, but this ID doesn't correspond to anything in the platform.

In our case, all the entities that are needed are supposed to be created by the CSV mapper itself. Perhaps the bug is that in some cases, entities contained in the file are not created by the CSV mapper mechanisms ? Does the CSV mapper mismanage the order of the objects it has to create ? Or does it simply skip the creation of a certain entity ?

I don't know... Moreover, what's strange is that it doesn't react the same way on different platforms.

**Comment by nino-filigran** [comment] 2024-04-26 09:14
Yeah, there is for sure an issue here. Let's see what comes out of the investigation.

**Comment by richard-julien** [comment] 2024-05-18 10:20
> On the "demo" platform, you can find the CSV mapper "Test bug missing ref error" with the configuration.

The mapper seems to be no longer accessible.

Needs to be tested after reviewed and merged of https://github.com/OpenCTI-Platform/opencti/pull/6862

**Comment by Lhorus6** [comment] 2024-05-20 18:25
- Have we identified the problem?
- Do we have a workaround method (still using CSV)?

**Comment by richard-julien** [comment] 2024-05-22 11:44
Not 100%. Could be related to https://github.com/OpenCTI-Platform/opencti/issues/7020

**Comment by aHenryJard** [comment] 2024-05-23 18:02
FYI I reduce the csv size for the reproduction steps, this one has the same issue. But I still don't see which line is causing issue in order to investigate on related entities.
[Test-issue-6818-chunck3-3+_issue.csv](https://github.com/OpenCTI-Platform/opencti/files/15420773/Test-issue-6818-chunck3-3%2B_issue.csv)

**Comment by aHenryJard** [comment] 2024-05-31 06:04
So the issue is narrowed to this 2 lines in csv:
```
Alphv,ScreenConnect,29/06/2022,Group-IB: Fat Cats,https://www.group-ib.com/blog/blackcat/
Alphv,ConnectWise,23/02/2022,Internal (TIN),null
```

Which are visible in history of ScreenConnect/ConnectWise Tool:
![image](https://github.com/OpenCTI-Platform/opencti/assets/3634942/826550c4-fba4-4f1b-a392-32c27ce389dd)

**Comment by aHenryJard** [comment] 2024-05-31 06:42
Issue reproduced locally and https://github.com/OpenCTI-Platform/opencti/pull/7126 will fix this issues.

**Closed as completed** 2024-05-31 09:12 UTC
Labels: bug, solved, csv mapper
