### ISSUE TITLE
Running a report search resets table search order

### ISSUE THREAD

**Issue by damians-filigran** [LuatixHQ/opencti#9164] opened 2024-11-27 18:50 UTC
## Description

In the reports screen, if a user changes their search string, the sort order on the report date is lost.

## Environment

1. OS (where OpenCTI server runs): SaaS
2. OpenCTI version: 6.4.1
3. OpenCTI client: Nor known
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to reports. The sort 
2. Search for a term. Eg. "malware"
2. Click date column header to sort ASC by date
3. Click it again to sort DESC by date
4. Go to the table search box and type a new search (eg. "Ransomware")
5. Sort order is reset, and no longer DESC by date

## Expected Output

Any applied sort order should be retained

## Actual Output

Sort order is lost

## Screenshots (optional)

**Comment by nino-filigran** [comment] 2024-11-28 08:25
Not sure if this logic has been implemented at first. It makes sense from a functional point of view though.

**Comment by Archidoit** [comment] 2024-11-29 10:26
@nino-filigran @damians-filigran  It's not really a bug : indeed when you do a search, the ordering mode is automatically reset to '_score' -> entities are ordered according to their matching level regarding the search term. 

For instance, if you search for 'test', a report named 'test' will be ordered before a report named 'this is a test' and before a report with 'test' only in its description

**Comment by nino-filigran** [comment] 2024-11-29 10:35
Good shot, I forgot about this behavior. Only on some specific entities (the one supporting cards, you can then change the sorting of the result). 
Therefore, given this response @damians-filigran I'm closing this ticket if it's fine for you, given that it's not a bug (nor something that we would fix)

**Closed as completed by nino-filigran** 2024-11-29 10:35 UTC
Labels: bug, wontfix

**Comment by damians-filigran** [comment] 2024-11-29 10:44
Thanks @Archidoit and @nino-filigran , good call, I wasn't aware of that behaviour.

I'll feed this back to the user and advise a feature request if they'd like to have the option for it to behave differently.
