### ISSUE TITLE
Cannot modify the name of an entity if already present in the alias of the same entity

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4798] opened 2023-10-28 23:51 UTC
## Description

Cannot modify the name of an entity if already present in the alias of the same entity.

## Reproducible Steps

1. Create an intrusion set "Intrusion Set A"
2. Add the alias "Intrusion Set B" and "Intrusion Set A"
3. Try to modify the name with "Intrusion Set B"

**Comment by Megafredo** [comment] 2023-10-30 07:08
version 5.11.12
I cannot reproduce the error, for my part the modification of the intrusion to a name identical to the alias is carried out correctly.
Here is the process history :
![image](https://github.com/OpenCTI-Platform/opencti/assets/14902945/c372c63f-6e93-4827-a88d-d16af7aba138)

**Comment by SamuelHassine** [comment] 2023-10-30 07:13
Hello,

Try here: https://testing.octi.staging.filigran.io/dashboard/threats/intrusion_sets/49abddab-a325-43cb-8e65-ca0187d1a408.

To put test in the name.

**Comment by Megafredo** [comment] 2023-10-30 07:23
> Hello,
> 
> Try here: https://testing.octi.staging.filigran.io/dashboard/threats/intrusion_sets/49abddab-a325-43cb-8e65-ca0187d1a408.
> 
> To put test in the name.

Indeed on the linked page the name change does not work, I will look at that !

**Comment by Kedae** [comment] 2023-11-03 09:35
We have added this feature in 57786434, is that really a bug or a revert of that behavior ?

**Comment by SamuelHassine** [comment] 2023-11-06 08:17
Thanks a lot @Kedae @Megafredo, well done.

Can you please add a note in https://docs.opencti.io/latest/usage/deduplication/?

With a form like:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/8038a2e4-7a0e-4888-a975-e3761ef4457b)

Thanks!

**Comment by SamuelHassine** [comment] 2023-11-06 08:32
Still remaining case sensitive issue.

**Comment by nino-filigran** [comment] 2023-11-09 09:05
This is fixed by PR. But now: 
- If an entity already exists, starting with a capital letter, when a user creates a new entity with same name but lower case -> the first created entity has the newly created name in the labels. 
     - Example: 
     - First entity name = Hello
     - 2nd entity name = hello
     - Result: First entity will be named Hello and would have "hello" as label
- If an entity already exists, starting with a lower case, when a user creates a new entity with a different name AND capital case but with the entitiy 1 name as alias, the first entity name gets changed, and becomes a label.
     - Example 
     - Entity 1 name = hello
     - Entity 2 = Day
     - New name of the entity = Day with hello label. 
 
The question is: is that a normal behavior ? If not, what would be the correct one?
@Megafredo please feel free to add a new comment to rephrase my comment if I got it wrong.

**Closed as completed** 2023-12-02 18:21 UTC
Labels: bug, solved
