### ISSUE TITLE
Allow relation "attributed-to" for threat actor groups to organizations

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#7821] opened 2024-07-26 10:10 UTC
## Use case
I want to state that APT28 (TAG) is attributed to the GRU (Org).

## Current Workaround
Use related-to realtionship

## Proposed Solution
Allow to use attributed to for TAGs to Orgs.

## Additional Information
While for intrusion sets it is possible to be attributed to a threat actor I share more the pov which is stated here https://github.com/OpenCTI-Platform/opencti/issues/2229, that an intelligence agency is more an org than a threat actor.
While TAGs and Intrusion Sets can be used interchangeable in reality maybe also Intrusion Sets should be capable to being attributed to an org.

**Comment by nino-filigran** [comment] 2024-11-29 14:34
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/8914

**Closed as completed by nino-filigran** 2024-11-29 14:34 UTC
Labels: duplicate, feature
