### ISSUE TITLE
[Playbooks] "Reduce knowledge" component doesn't act on the original entity

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5989] opened 2024-02-15 18:35 UTC
## Description

I try to retrieve the observables linked to a report and label them (but not the report) with the playbook.

So I make a playbook like this:
1. Listener on modification event, with filters "entity:report + label:test"
2. Apply predefined rule : resolve container references
3. Reduce knowledge with filter "entity:observables"
4. Manipulate knowledge: add a label to all entities in the bundle
5. Send to ingestion

But in the step 4, I still have the report inside the manipulated bundle (that should not be there thanks to the "reduce knowledge" component)

## Environment

OCTI 5.12.31
Filigran prod instance 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create the playbooks as describe in the description
2. Trigger the playbooks by applying the label "test" on a report containing observables
-> The report is labeled because it is still in the bundle after the "reduce knowledge" component

## Additional information

You can go on the filigran prod instance and look for the playbook "Bug reduce knowledge" that will help to debug

![Screenshot 2024-02-15 193223](https://github.com/OpenCTI-Platform/opencti/assets/70956706/d1ab4e6d-3ad9-4dd1-98a5-e0455682c515)

**Comment by Kedae** [comment] 2024-02-16 08:18
This is the expected behavior, Reduce Knowledge doesn't remove the "main" entity that triggered the workflow.
I'll let you talk with @richard-julien if you think this need to be modified in the future but I'm closing this issue for now as this is not a bug.

**Closed as completed by Kedae** 2024-02-16 08:18 UTC
Labels: bug, wontfix
