### ISSUE TITLE
Promote observables to indicators and vice versa in the context of a container should add to container the new entity and the base-on relation

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7294] opened 2024-06-09 10:43 UTC
## Use case

Promote observables to indicators and vice versa in the context of a container should add to container the new entity and the base-on relation

**Comment by Lhorus6** [comment] 2024-06-09 18:42
May be a duplicate of this one : https://github.com/OpenCTI-Platform/opencti/issues/6171

**Comment by nino-filigran** [comment] 2024-06-11 09:59
Yes, it's a duplicate. @SamuelHassine I'm closing this ticket, to only keep one.

**Closed as completed by nino-filigran** 2024-06-11 09:59 UTC
Labels: duplicate, feature
