### ISSUE TITLE
Available statuses are not displayed in the live trigger creation/modification window

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4525] opened 2023-10-09 09:13 UTC
## Description

Available statuses are not displayed in the live trigger creation window

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 5.10.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Login as admin
2. Go to Settings -> Security -> Users -> Username
3. Click on "Add a live trigger" 
4. Click on "Filters"
5. Choose "Entity type:Report" filter
6. Choose "Status" filter

## Expected Output

List of available report statuses:
- NEW
- UNPROCESSED
- IN_PROGRESS
- PROCESSED

## Actual Output

No available options.

## Screenshots
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/a0fccd61-e0c3-450c-a72b-9dee0eb6be27)

**Comment by Archidoit** [comment] 2023-10-09 12:01
I can't reproduce your issue...
If you select a status before selecting an entity type filter, do you still have nothing in the status dropdown? Are you sure the status workflow is enabled in Customization > Report ?

**Comment by rattat0r** [comment] 2023-10-09 15:16
If I select status before selecting the object type filter, there is still nothing in the status dropdown. I think status workflow is enabled

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/1f868fa6-8dae-492b-b063-941850f7bdda)

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/b2939a2b-c230-4538-b5ec-e30c44786657)

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/87116147-ca65-4c2d-bc05-dde39861f216)

**Comment by Archidoit** [comment] 2023-10-09 15:19
Mm indeed report workflow status seems enabled in your 2 last screenshorts... but the first one should be : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/f16ea166-f14b-4c77-8402-06b7e3118331)

**Comment by Archidoit** [comment] 2023-10-09 15:20
Your first and second screenshort are contradictory... that's strange

**Comment by rattat0r** [comment] 2023-10-09 17:07
What other information can I provide to help resolve this issue?

**Comment by richard-julien** [comment] 2023-10-12 07:31
Hi @rattat0r , if i remember well for now this filter only show currently used workflow status. Can you try to create a Report and assign it a status and then recheck the content of the selector? Thanks.
(I will take a look to change this behavior that doesnt look really smart when configured triggers :))

**Comment by rattat0r** [comment] 2023-10-13 08:23
At the moment I have many reports with status NEW and IN_PROGRESS, but they are not showing up in the live trigger filter.
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/1fcb8525-581e-4907-ac33-ac34190f9cab)

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/9aee7b26-5203-4767-88fc-23d361dff3c1)

**Closed as completed** 2023-10-14 21:42 UTC
Labels: bug, solved
