### ISSUE TITLE
[api/worker/client] OpenCTI does not support self-signed CAs for RabbitMQ worker/connector connections.

### ISSUE THREAD

**Issue by max-frank** [LuatixHQ/opencti#2309] opened 2022-09-01 00:55 UTC
## Description

As of writing the OpenCTI platform does not support self-signed CAs for use with RabbitMQ for both workers and connectors due to limitations in the way RabbitMQ configuration is done and limited configurability of the OpenCTI python client. See also https://github.com/OpenCTI-Platform/opencti/issues/2308 for a similar issue affecting the API RabbitMQ connection. Also Note I am creating this issue as bug since the existing API configuration `RABBITMQ_CA` makes it seem like self-signed CAs are supported while due to below described issues in the code it is not.

Multiple related issues need to be fixed to solve this I will try my best to list everything I noticed, but due to lack of understanding I might have missed something.

### RabbitMQ configuration is only read from the API and is missing necessary configuration options

Now let me preface this with that passing all of the RabbitMQ configuration (including **credentials**) to workers/connectors via  an API call is not very great from a security standpoint. It also slows down development/adoption of new connection configuration options, since modification to support new options would have to be made in multiple parts of the code base. So ideally anything, but the listen/push queues specific to what ever work load being worked on by a connector should be configured on the Worker/Connectors directly.  This is especially true for RabbitMQ credentials right now everything shares the RabbitMQ credentials configured for the API server making creation of sane ACL impossible.

The API call in question is configured [here](https://github.com/OpenCTI-Platform/client-python/blob/21a75a73289692c334152877520cf52c6f3c6875/pycti/api/opencti_api_connector.py#L14) and will only return a boolean flag `use_ssl`. Meaning the `RABBITMQ_CA` option is not passed forward to connectors/works, though even if it is passed forward it would not make any sense as file paths for CA files are likely to be different between API and Worker systems. So as mentioned above even if it is possible to forward the already existing CA option to via this endpoint it would not make sense and instead the `connection` configuration here should be removed and replaced with local configuration options for the python client.

### Worker/Python Client SSL configuration does not support setting CA options (neither custom CA or client certificates)

Workers/Connectors ultimately [create_ssl_context](https://github.com/OpenCTI-Platform/client-python/blob/c3bcebd4e02cd8e5664c4126ab497a2097f44ba3/pycti/connector/opencti_connector_helper.py#L77) is used by workers/connectors to configure the Pika SSL options. This function/the whole configuration flow here does not allow for setting any custom TLS options. So it is not possible to configure custom CA paths or client certificates. See the [Pika documentation](https://pika.readthedocs.io/en/stable/examples/tls_mutual_authentication.html) on what would be necessary to enable support for this in the code.

## Environment

1. OS Alpine Linux v3.16
2. OpenCTI version: 5.3.8
3. OpenCTI client: -
4. Other environment details: k8s deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure OpenCTI to use TLS with a self signed certificate for RabbitMQ
2. Start the thing
3. Workers/Connectors will fail due to TLS verification errors.

## Expected Output

Working TLS with self signed certs and ideally mTLS support.

## Actual Output

No support for either.

**Comment by max-frank** [comment] 2022-09-01 00:56
Please feel free to ask for additional info/clarification. The underlying issue is so broad that I might have gotten lost in the details.

**Comment by SamuelHassine** [comment] 2022-10-02 18:20
Duplicate of #2308.

**Closed as completed** 2022-10-02 18:20 UTC
Labels: duplicate, feature
