### ISSUE TITLE
CSV mapper stops importing if an error occurs

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6370] opened 2024-03-15 13:49 UTC
## Description

When importing a file, if an error occurs, the mapper stops rather than moving on to the next line.

Example:

On each line I import an intrusion set, an IPv4 and I make the relation between the two. If on a line I don't have the intrusion set linked to my IPv4, I'll get an error because the representation of the intrusion set will crash because there's no name. However, it would be desirable for the error to be caught, then for the mapper to continue on to the line below.

## Environment

OCTI 6.0.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a mapper mapping an intrusion set, an IPv4 and a relation between them.
2. Create csv file with two columns (one for IPv4, one for intrusion set) and 3 rows. In the second row, let the intrusion set column empty.
3. Import the file
-> You should not retrieve the entities contained in the third line, because the second one crash and stopped the import.

**Comment by jborozco** [comment] 2024-03-18 08:20
I'm adding a csv file to reproduce 
[test.csv](https://github.com/OpenCTI-Platform/opencti/files/14632962/test.csv)

**Comment by JeremyCloarec** [comment] 2024-03-20 10:42
I wasn't able to reproduce it locally. I created the csv mapper config, and when importing the test.csv file, I have 4 entities created (all 3 instrusions sets and 1 IPv4 observable) as well as 2 relationships created (intrusion1 <-> IP and intrusion3 <-> IP).
It looks like it was fixed with #6151 ?

**Comment by SamuelHassine** [comment] 2024-04-18 21:46
It is fixed.

**Closed as completed by SamuelHassine** 2024-04-18 21:46 UTC
Labels: bug, solved, csv mapper
