### ISSUE TITLE
Sidebar sections do not match user capabilities

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#6328] opened 2024-03-13 08:43 UTC
## Description

When the "Access administration" right is disabled, the "Processing" section is still displayed in the sidebar. If you try to go to the "Processing" section, you will be redirected to the authorization page. (see screenshots)

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 6.0.4
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Remove the "Access administration" right from the user role.
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/2fa784a7-ce46-4cb9-823b-252eaa8dce7f) 
2. The "Processing" section is still displayed on the sidebar, but it is of no use because there is no access to it. Clicking on this section will redirect you to the login page.
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/902ebae3-07ac-4871-93f0-b8480dd4a1d4)

## Expected Output

The sidebar shows only available sections. In this case, without the "Processing" section.

## Actual Output

The sidebar displays sections that are not available for interaction.

**Comment by nino-filigran** [comment] 2024-03-14 08:09
@rattat0r can you please confirm that you do not have the following right: manage CSV mapper? and Bypass all capabilities? I guess you don't but just want to confirm this. At the same time, could you please provide the rights that your user have, so that I can reproduce the exact same case?

**Comment by nino-filigran** [comment] 2024-03-14 08:13
I'm able to reproduce this bug with a user having the following rights

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/32683c59-94af-48c2-b2e8-8e4ce267ca88)

**Comment by SouadHadjiat** [comment] 2024-03-14 08:57
Processing menu should still be displayed to be able to access to "CSV mappers" and/or "Tasks" depending on the capabilities (for tasks you only need to have "Create / Update knowledge" capability").

This issue is a duplicate of #6312

**Comment by SouadHadjiat** [comment] 2024-03-14 13:40
solved with https://github.com/OpenCTI-Platform/opencti/pull/6340

**Closed as completed by SouadHadjiat** 2024-03-14 13:40 UTC
Labels: bug, duplicate
