### ISSUE TITLE
Split capability "Manage labels & Attributes" into 2 capabilities

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3527] opened 2023-06-15 12:05 UTC
## Use case

Split the capability "Manage labels & Attributes" into:

* Manage labels
* Manage attributes

Indeed, to cover this use case: 

> I have a connector account with connector role that has the default permissions, except the `Manage labels & Attributes`.
> I would like to be able to enable connectors and have them create automatically the report types OV but not labels.

**Comment by Jipegien** [comment] 2023-07-25 15:02
linked to #3757

**Comment by Jipegien** [comment] 2024-02-27 12:17
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/5550

**Closed as not planned by Jipegien** 2024-02-27 12:17 UTC
Labels: duplicate, feature
