### ISSUE TITLE
Bulk Enrichment option doesn't show unless you mark observable type on right menu

### ISSUE THREAD

**Issue by EinatAR** [LuatixHQ/opencti#8696] opened 2024-10-17 18:59 UTC
## Description

When bulk selecting a list of observables in a report, the enrichment icon doesn't show in the bottom menu.
It then shows if you also click select the observable type on the right side menu.

## Environment

OpenCTI version: 6.3.6

## Reproducible Steps

1. Go to a Report > Observables tab 
2. Filter on an observable to get a full list
3. Check the upper box to bulk select the whole list of observables -> no enrichment option as expected.

Example: 
![Screenshot 2024-10-17 at 20 49 09](https://github.com/user-attachments/assets/ed599e80-3157-44a0-b6cc-7d208848da2c)

4. Now click select also the chosen observable type on the right side menu and the enrichment icon will appear.

Example: 
![Screenshot 2024-10-17 at 20 54 12](https://github.com/user-attachments/assets/a96da2bd-4c0b-454f-b478-9b1bbfac61de)

## Expected Output

Should see the enrichment icon at the bottom right when bulk selecting the observables list.

## Actual Output

Missing the Enrichment icon (appears only when selecting also the Observable type on the right side menu)

**Comment by nino-filigran** [comment] 2024-10-18 07:17
@EinatAR did you use the select all functionality? If so, it's not a bug but a feature, that we aim to deliver this release https://github.com/OpenCTI-Platform/opencti/issues/5582

**Comment by EinatAR** [comment] 2024-10-18 08:07
@nino-filigran Yes, it is the select all button, similar to the issue you mentioned :-)

**Comment by nino-filigran** [comment] 2024-10-18 08:56
Great, then I'm closing this ticket if that is fine for you :) 
Feel free to re-open it if you do not agree.

**Closed as completed by nino-filigran** 2024-10-18 08:56 UTC
Labels: bug, duplicate
