### ISSUE TITLE
Marking Definition field does not populate when there are a large number of custom marking definitions

### ISSUE THREAD

**Issue by TechBurn0ut** [LuatixHQ/opencti#2437] opened 2022-10-08 16:17 UTC
## Description

We heavily use custom marking definitions to ensure that we have data segregation between our constituents.  As a result, we have ~200+ custom marking definitions.  The issue is when creating or updating objects in the UI, the Marking Definition field never populates with the list of markings.

## Environment

1. OS (where OpenCTI server runs): AWS Linux 2
2. OpenCTI version: 5.3.16
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a list of custom marking definitions (100+)
2. Try to create a new object
3. Click on the Marking field -> List does not populate

## Expected Output

The list of Marking definitions to populate so that it can be properly assigned to the object.

## Actual Output

List never populates

## Additional information

Can provide information, please contact `Jason Maurath` in Lautix/OpenCTI Slack

**Comment by richard-julien** [comment] 2022-10-08 16:29
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2436 ?

**Comment by SamuelHassine** [comment] 2022-10-08 17:51
Yes duplicate. It just appears in the latest versions.

**Closed as completed** 2022-10-08 17:51 UTC
Labels: bug, duplicate
