### ISSUE TITLE
Export User History

### ISSUE THREAD

**Issue by rabbipigeon** [LuatixHQ/opencti#2250] opened 2022-07-25 09:22 UTC
## Use case

When Working as a part of a team, it would be beneficial to be able to see what each user has done. If i can export history or have a dashboard where i can see that. It would be helpful.

## Current Workaround

Go to user and search through the history

## Proposed Solution

At minimum, export to csv option.

**Comment by Jipegien** [comment] 2023-07-27 12:14
duplicate of #3631

**Closed as not planned by Jipegien** 2023-07-27 12:14 UTC
Labels: duplicate, feature
