### ISSUE TITLE
Filters on data sharing streams are not honoured

### ISSUE THREAD

**Issue by misje** [LuatixHQ/opencti#7198] opened 2024-05-31 06:48 UTC
## Description

Setting a filter on a shared data stream, like "Entity type != URL", does not seem to have any effect.

## Environment

1. OS (where OpenCTI server runs): docker
2. OpenCTI version: 6.1.6
3. OpenCTI client:
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a shared data stream
2. Apply a filter, like "entity type != URL"
3. Import data from the stream in another OpenCTI instance, doing nothing and ingesting nothing
4. Watch unwanted entities being imported

## Expected Output

No URL SCOs in the second OpenCTI instance.

## Actual Output

URL SCOs are imported.

**Comment by nino-filigran** [comment] 2024-06-03 07:14
@misje Can you try to upgrade your version? I cannot reproduce it on 6.1.8 on our demo environment!

**Comment by nino-filigran** [comment] 2024-06-19 08:22
@misje did you try the above solution? Given I've not reproduced on the current version, I'm closing this issue. Please let me know if the problem persists after your upgrade, and if it's the case, feel free to reopen it!

**Closed as completed by nino-filigran** 2024-06-19 08:22 UTC
Labels: bug, wontfix, filters & search

**Comment by misje** [comment] 2024-06-23 17:59
I've verified that this appears to work now with both servers running 6.1.12.

**Comment by misje** [comment] 2024-06-23 18:06
I'm getting first-neighbour releationships, of course, but I am sure that is by design.
