### ISSUE TITLE
[Dashboard] filter on first/last seen doesn't work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7108] opened 2024-05-23 21:26 UTC
## Description

When I set my widgets with "date attribute" to first seen (or last seen), filtering on dates (which can be done at the global dashboard level, next to the dashboard's name) does not seem to work.

## Environment

OCTI 6.1.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a dashboard
2. Create a widget "Donuts > Knowledge graph" with this filters:

![Screenshot 2024-05-23 230824](https://github.com/OpenCTI-Platform/opencti/assets/70956706/62d29ea8-485d-464a-98b6-43a143a10db7)

3. And this parameters

![Screenshot 2024-05-23 230834](https://github.com/OpenCTI-Platform/opencti/assets/70956706/f62e2f78-5725-4378-88f3-def77baa08c6)

4. Create three two Incidents containing one Attack pattern and with first seen set at 01/01/2024, 01/03/2024, and 01/05/2024
5. Apply the label "anel" on the three Incident (to match the filters of the widget)
6. Check your widget -> you can see three elements in the donuts (the three Attack pattern)
7. Then play with the "relative time" filter
-> As soon as a date is set, no matter which one, you will no longer have anything on your widget

NB: you can check with what is already in place on the testing platform:
- The dashboard -> widget "Test bug on knowledge perspective": https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/d89c9638-fd7c-42a7-a3b0-97c452f36307
- The incident 1: https://testing.octi.staging.filigran.io/dashboard/events/incidents/f3634a3c-ba3f-41c4-a663-44c4e4e7d640
- The incident 2: https://testing.octi.staging.filigran.io/dashboard/events/incidents/0df58dc5-6a17-425a-9913-269c54c3d21c
- The incident 3: https://testing.octi.staging.filigran.io/dashboard/events/incidents/d1a85bf0-b5ac-4e81-82df-08e1e159917a

## Additional information

On an Entities perspective, the bug does not appear. Do like this:
1. Create a dashboard
2. Create a widget "Donuts > Entities" with this filters:

![Screenshot 2024-05-23 231712](https://github.com/OpenCTI-Platform/opencti/assets/70956706/da4eb6b6-12a4-4584-a2cd-b59cbe06976d)

3. And this parameters

![Screenshot 2024-05-23 231719](https://github.com/OpenCTI-Platform/opencti/assets/70956706/28e815e3-34b9-4cfa-b2ba-0224ebc5601e)

4. Create three two Incidents containing one Attack pattern and with first seen set at 01/01/2024, 01/03/2024, and 01/05/2024
5. Apply the label "anel" on the three Incident (to match the filters of the widget)
6. Check your widget -> you can see three elements in the donuts (the three Incidents)
7. Then play with the "relative time" filter
-> As soon as a date is set, no matter which one, you will no longer have anything on your widget

NB: you can check with what is already in place on the testing platform:
- The dashboard -> widget "Test on entities perspective": https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/d89c9638-fd7c-42a7-a3b0-97c452f36307
- The incident 1, 2, 3: The same three as in the repro case above

## Assumption

From the “knowledge graph” perspective we are focusing/filtering on relationships. The relationships are therefore the “main” objects. When we set the "date attribute" maybe it's relationship dates only (and not entity dates that end up being displayed on the widget). If this is the case (i.e. we cannot reach the dates of objects at the end of the relation), as the relations do not have "first seen" and "last seen" (they have "start time" and " stop time"), then the widget remains empty as soon as there is a time filter.

When we are in the "Entities" perspective, this time we filter on the Incident entities which have "first seen" and "last seen". So it works.

This wouldn't be a bug. However, we have a customer who tells me that it worked before, so I have my doubts. Looking in the code should be able to tell if it's a bug or if it's my assumption that is correct

**Comment by nino-filigran** [comment] 2024-05-24 08:48
@Lhorus6 I cannot say whether or not it was something existing or not, but I'm not sure its a bug: 
- using a knowledge perspective, using the attribute "start time" works, both when displaying AND when playing with filters
- using a knowledge perspective, using the attribute "first seen" works partially: it only displays data when date fitlers on the dashboard are not enabled
- using an entity view, displaying incidents and showing the attribute "first seen"  works: it shows me 0.

I don't think it's a bug: 
- in relations, **start time** and **stop time** are used as date attributes
- in sightings, **first seen** and "last seen" are used as date attributes
- in entities, creation date (technical & functional) are used.

Therefore, to me this is not a bug, but rather a not so good UI, since we offer to display values based on fields that do not exists. I might be wrong, because I have not played a lot with dashboards. 
I'm not closing it though, to make sure you can test and ensure that this seems right.

**Comment by Lhorus6** [comment] 2024-05-24 13:53
I'm exactly of the same opinion as you. You described exactly what I tried to describe in my issue but with more talent haha ^^

Like you, I don't know if it's a bug, and that's why I ended my issue by saying :
This wouldn't be a bug. However, we have a customer who tells me that it worked before, so I have my doubts. **Looking in the code should be able to tell if it's a bug or if it's my assumption that is correct**

Would it be possible to have this checked?

**Comment by nino-filigran** [comment] 2024-05-27 07:03
Yeah, sure, just asked for it this morning.

**Comment by nino-filigran** [comment] 2024-05-27 07:46
@Lhorus6 I confirm: it's because

- in relations, start time and stop time are used as date attributes: therefore, choosing any other attribute won't work
- in sightings, first seen and "last seen" are used as date attributes:  therefore, choosing any other attribute won't work
- in entities, creation date (technical & functional) are used:  therefore, choosing any other attribute won't work

**Comment by nino-filigran** [comment] 2024-05-27 07:51
I'm closing this issue since it's not a bug, but I've created a feature request to ensure we improve which dates are selected according to the context: https://github.com/OpenCTI-Platform/opencti/issues/7128

**Closed as completed by nino-filigran** 2024-05-27 07:51 UTC
Labels: bug, wontfix
