### ISSUE TITLE
Be able to change mail logo

### ISSUE THREAD

**Issue by remydewa** [LuatixHQ/opencti#2038] opened 2022-04-25 12:02 UTC
## Use case

OpenCTI is able to send email like this one

![Screenshot from 2022-04-25 13-55-38](https://user-images.githubusercontent.com/53039170/165084346-d6dbf1f3-0bd8-4c60-ae80-2dd004c17091.png)

But It's not possible, to my knowledge, to change the OpenCTI logo with a brand logo.

## Proposed Solution

As it's already possible to change the login page logo, the menu logo, make it possible to change the logo for the email.

## If the feature request is approved, would you be willing to submit a PR?

Currently, unfortunately no

**Comment by SamuelHassine** [comment] 2022-10-02 17:37
Duplicate of #1871

**Closed as completed** 2022-10-02 18:17 UTC
Labels: duplicate, feature
