### ISSUE TITLE
Allow customization of Infrastructure Types

### ISSUE THREAD

**Issue by TechBurn0ut** [LuatixHQ/opencti#2294] opened 2022-08-22 16:52 UTC
## Use case

As an Analyst, I require the ability to customize/define Infrastructure Types in order to better classify Infrastructure Objects.  

## Current Workaround

There is currently no work around for this customization.

## Proposed Solution

I believe the current implementation is leveraging the STIX `infrastructure type` field, I would like the ability to customize that list.  If customization of that field is limited due to STIX, I would suggest a new custom field that allows the operator the ability to categorize Infrastructure types.  Examples: `Email Server`, `Microsoft Exchange`, or `Domain Controllers`.   Then leveraging SCOs, an Operator could better describe a targeted environment.

## Additional Information

<img width="891" alt="Screen Shot 2022-08-22 at 11 37 24 AM" src="https://user-images.githubusercontent.com/30411037/185975982-451e0ef2-4108-4f9c-98bd-5c9abe5cc744.png">

## If the feature request is approved, would you be willing to submit a PR?

No - Would be willing, but not familiar enough with the project to implement.

**Comment by SamuelHassine** [comment] 2022-10-02 18:18
Duplicate of #1602

**Closed as completed** 2022-10-02 18:19 UTC
Labels: duplicate, feature
