### ISSUE TITLE
Enable quick dashboard deployment, streamline custom workflows, and potential external sharing

### ISSUE THREAD

**Issue by Astral-Reaper** [LuatixHQ/opencti#3076] opened 2023-03-28 02:42 UTC
## Use case

Facilitate quick dashboard and customized work flow creation.

## Current Workaround

Manually create every dashboard.

## Proposed Solution

Enable the copying/duplication of any existing dashboards and renaming, as appropriate, to deploy new or tailored versions.

## Additional Information

Rather than having to create dashboards from scratch over and over again. Being able to copy/duplicate any existing dashboard, including the openCTI pre-defined one would extremely speed up the process of custom work flows or specific data visualizations.

- Maybe even the potential to export dashboard configurations for external sharing.

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by Jipegien** [comment] 2023-05-30 13:33
Duplicate of issue #3241

**Closed as completed by Jipegien** 2023-05-30 13:33 UTC
Labels: duplicate, feature
