### ISSUE TITLE
Add boolean selection in research parameters

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1679] opened 2021-10-25 17:30 UTC
## Use case

When setting parameters for which there can be several choices (most common case are labels), by default it is a "OR" boolean which is implemented and it cannot be changed.

When setting the parameters of a research, the booleans should be also parameters. The choice should be possible between OR, AND and NOT.

![Capture d’écran du 2021-10-25 19-27-10](https://user-images.githubusercontent.com/49722941/138742516-77019ea8-60e6-401f-838a-1e6389f36396.png)

**Comment by SamuelHassine** [comment] 2022-10-02 14:54
Linked to #1528.

**Comment by SamuelHassine** [comment] 2023-05-18 17:50
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2686

**Closed as completed** 2023-05-18 17:51 UTC
Labels: duplicate, feature
