### ISSUE TITLE
Bulk Change of status

### ISSUE THREAD

**Issue by rabbipigeon** [LuatixHQ/opencti#2009] opened 2022-04-04 09:48 UTC
## Use case

I Have a large number of reports that have ingested that im not interest in. It is not feasible for me to sit here and change the status of 1000 reports. It would be nice if this was added to the current available option where you can select all or by filter and bulk change author,confidence , labels etc... 

## Current Workaround

None

## Proposed Solution

Status to be a "replace" option in the bulk change feature

## If the feature request is approved, would you be willing to submit a PR?

Perhaps (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment] 2022-04-05 10:52
Duplicate of #1566.

**Closed as completed by SamuelHassine** 2022-04-05 10:52 UTC
Labels: duplicate, feature
