### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by AlexForensic** [LuatixHQ/opencti#8749] opened 2024-10-23 09:17 UTC
Hello, 

i meet this error when i try the command "yarn install" : 
![image](https://github.com/user-attachments/assets/173885bf-35e8-412d-85eb-59c304cc84d7)
version 6.3.6 
os debian 12

Thanks

**Comment by Kedae** [comment] 2024-10-24 09:11
Duplicate of #8755

**Closed as not planned by Kedae** 2024-10-24 09:11 UTC
Labels: question, solved
