### ISSUE TITLE
[FEATURE] Add Organization based / More advanced RBAC 

### ISSUE THREAD

**Issue by mwatermolen** [LuatixHQ/opencti#2245] opened 2022-07-21 16:12 UTC
## Use case

We would like to allow clients to be able to login to opencti to see their observables / incidents / sightings / relationships.

## Current Workaround

This can be done by adding Markings for each company, however this is hard to manage and not very scalable

## Proposed Solution

Implement true Org / Entity based RBAC, allowing for isolation of Cases(future), sightings, etc. Allowing for multi-tenancy use

## Additional Information

N/A. Feel free to ping me on slack, this is kinda an abstract request

## If the feature request is approved, would you be willing to submit a PR?

Yes (But this is gonna be way over my head / time atm)

**Comment by richard-julien** [comment] 2022-07-21 16:17
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2188 ?

By the way any idea of how storing that? Today STIX only have a list of markings that i think are cumulative, like the current OCTI implementation. If you want to add some kind of OR between markings, how do you think we can structure that and export it? If have some starting idea in mind but I dont want to influence :)

**Closed as completed** 2022-08-20 11:35 UTC
Labels: duplicate, feature
