### ISSUE TITLE
Granular permissions for downloading artifacts

### ISSUE THREAD

**Issue by shadow-helix** [LuatixHQ/opencti#7221] opened 2024-06-04 09:39 UTC
## Use case

To allow for more granular permission structures based on team roles and responsibilities, which would allow different levels of team member to be able to download artifacts (or not).

## Current Workaround

No workaround available

## Proposed Solution

Additional role capability to enable/disable the ability to download artifacts.

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment] 2024-06-24 08:27
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/7292

**Closed as completed** 2024-06-24 08:27 UTC
Labels: duplicate, feature

**Comment by shadow-helix** [comment] 2024-06-24 22:29
Disagree that this is a duplicate; firstly, this issue was raised before #7292, so if anything that would be a duplicate of this. However, both issues are for different things.

**Comment by nino-filigran** [comment] 2024-06-25 08:03
@shadow-helix yes, they are not 100% similar, but at least on our side both are about to: 
- add a capability to download (or not) artifacts.
When working on it, we will aslo take into the slightly different scope of the other ticket (download as raw). This is simply easier to track.
