### ISSUE TITLE
Duplication of screen to filter on entity type

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8153] opened 2024-08-23 09:43 UTC
## Description

In the "Entities" and "Observables" tabs of the containers (e.g. Report, Grouping, Cases), the filter on entity types is somehow duplicated, see screenshot:

![Screenshot 2024-08-23 114126](https://github.com/user-attachments/assets/7c52c374-d244-486b-940c-b93eb4ca4e7e)

PS: Product, it's maybe not a bug but a feature, I'll let you recategorize if necessary

## Environment

OCTI 6.2.14

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on a Report
2. Check the "Entities" and "Observables" tabs

**Comment by Jipegien** [comment] 2024-08-26 07:18
duplicate of [#7574](https://github.com/OpenCTI-Platform/opencti/issues/7574)

**Closed as not planned by Jipegien** 2024-08-26 07:18 UTC
Labels: bug, duplicate
