### ISSUE TITLE
CSV mapper configuration can mix up entity types fields

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#5751] opened 2024-01-30 14:30 UTC
## Description

When creating/updating a CSM mapper, changing the entity type in a representation can lead to strange behavior, where fields from the previous type are somehow still present after changing the entity type. 

This makes incorrect configuration possible, as these fields do not exist for these entity types.

## Environment

TESTING

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new CSV mapper
2. Add a representaion
3. Select 'URL' entity type > pay attention to the fields displayed
5. Select 'File' > pay attention to the fields displayed
6. Re-select 'URL  > pay attention to the fields displayed

## Expected Output

The form shall display the URL attributes, same as the first time.

## Actual Output

The attribute "observable content" is somehow still present (it was in the "File" form).

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/dedf607f-c675-4696-a5d4-51dc7c24ccb6)
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/25a2c8d2-8c2e-43ae-abc6-8a670754130c)
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/7c56cb14-de08-4ea8-93f7-d354c2e7f0f8)

**Comment by labo-flg** [comment] 2024-01-30 14:30
cc @Goumies and @lndrtrbn 

Your current work on the CSV mappers could fix this maybe?

**Comment by lndrtrbn** [comment] 2024-01-31 08:13
I'll have a look in my current PR about CSV Mapper

**Comment by lndrtrbn** [comment] 2024-01-31 08:49
Ok it seems the issue came for the specific case of File where there are two attributes with the same name `obsContent`, don't know what it means yet and one of them is not removed when changing to an other entity

**Comment by richard-julien** [comment] 2024-01-31 09:01
obsContent is always defined once in the file model. Maybe a problem of view reset

**Comment by lndrtrbn** [comment] 2024-01-31 09:03
Well it is defined once in schema attribute and once in schema ref, with the same name. So as we use both in the csv mapper, we have an issue

EDIT: as the issue is related to the schema and not the csv mapper I won't fix it in my PR but in a dedicated issue after.

**Closed as completed** 2024-01-31 11:10 UTC
Labels: bug, solved, csv mapper
