### ISSUE TITLE
Incorrect display of pdfs with landscape and portrait pages

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4819] opened 2023-10-31 10:34 UTC
## Description

In "Content" tab, a pdf file containing pages in portrait AND landscape mode is displayed incorrectly. All pages are in landscape mode which produces:

- The original pages in landscape mode are displayed normally
- The original pages in portrait mode are embedded in landscape mode and therefore make up half of the page (see screenshot)

## Environment

OpenCTI 5.11.12

## Reproducible Steps

1. Upload a pdf file containing pages in portrait mode and others in landscape mode (example in attachment) in a Report
2. Go on the "Content" tab
3. Check the pdf file imported

## Expected Output

Have the pages in normal portrait as when opening the PDF normally (and not embedded in a landscape view)

## Screenshots

<img width="1721" alt="Screenshot 2023-10-31 113029" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/7447803d-128f-4f67-a4f9-30cbc32c7a14">

[File_to_test.pdf](https://github.com/OpenCTI-Platform/opencti/files/13215207/File_to_test.pdf)

**Comment by marieflorescontact** [comment] 2023-11-01 10:17
Hi @Lhorus6 ,
if you scroll down can you see 1st page in full ? 
I can't reproduce the bug. I do have the 1st page embedded in a landscape mode, but it's full and the pdf export is correct too.
The content tab allows you to preview, but it's still a preview.
if you want to open the document quickly in the browser, go to the data tab and click on the document name.

**Comment by Lhorus6** [comment] 2023-11-01 11:13
Hi Marie
Yes full page presents, just a matter of view. If it is known that portrait pages can be embedded in landscape pages and that is good for you, then we can close this issue, no problem :)

**Comment by marieflorescontact** [comment] 2023-11-01 14:01
For me it is not  a bug but more a general improvement of the content tab to be expected.

after investigation, here's what I found:
each pdf page in preview is displayed via a Page component in `StixDomainObjectContent.jsx`:

```
  <Page
      key={}
      pageNumber={index + 1}
      height={height}
      scale={this.state.pdfViewerZoom}
   />
```
there is a `rotate` property. it would be nice to use it according to each page orientation of the input document, but I haven't figured out how yet.

there is a [second open issue](https://github.com/OpenCTI-Platform/opencti/issues/4501) concerning this `StixDomainObjectContent` component, could be great to take the product team on a tour of the component to think about a general improvement.

**Comment by nino-filigran** [comment] 2023-11-03 08:24
Hey @Lhorus6 it seems that it has already been identified by our team: https://github.com/OpenCTI-Platform/opencti/issues/2950 
Please keep track of this ticket to know when this will be fixed.

**Closed as completed** 2023-11-03 13:09 UTC
Labels: duplicate, feature
