### ISSUE TITLE
Bug in file import if same name and same location

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4631] opened 2023-10-17 08:56 UTC
## Description

Importing two files with different contents but originating from the same local location and with the same name will produce the same workbench (the workbench will be that of the first file imported).

## Reproducible Steps

1. Download the STIX bundle in attachment (or create a file to import yourself) 
2. Import the file into the platform
3. View the workbench
4. On the platform, delete the imported file and the associated workbench
5. Open your file with an editor on your computer and delete all its contents to make it empty
6. Re-import the file 
7. Look at the workbench: it's the same as the previous one, but the file is currently empty.

If you change the file name before importing it again, this problem does not occur.

## Attachment
[test_debug.json](https://github.com/OpenCTI-Platform/opencti/files/12926534/test_debug.json)

**Comment by SouadHadjiat** [comment] 2023-10-17 09:57
I can't reproduce the issue, seems to be a cache issue (seen with @Lhorus6). Closing as not reproduced.

**Closed as not planned by SouadHadjiat** 2023-10-17 09:57 UTC
Labels: bug, wontfix
