### ISSUE TITLE
Adding Image to entity profile

### ISSUE THREAD

**Issue by AAA10CR7** [LuatixHQ/opencti#2349] opened 2022-09-13 14:51 UTC
I would like to request a new feature for different entities in OpenCTI where we can upload image that represent logo or flag of the entity .

For example, enable user to

1) upload photo of the individuals (actual photo)
2) add logo of the organization (Microsoft, Google ...etc)
3) upload Threat actor/intrusionSet image (IRGC, GRU, APT34)
4) flag image of the country (US, Italy, UK ...)

Also, it would be great if we can substitute current entity logo (repetitive for same type) with these images in different graphs ( investigation, knowledge)

**Comment by SamuelHassine** [comment] 2023-05-18 16:33
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2540

**Closed as completed** 2023-05-26 07:44 UTC
Labels: duplicate, feature
