### ISSUE TITLE
Cascade deletion at user deletion

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4026] opened 2023-08-10 06:56 UTC
## Use case

When we delete a user, some objects that are linked to the user are not deleted and can't be accessed anymore or are useless.

## Current Workaround

When we delete a user, only the user is deleted.

## Proposed Solution

At a user deletion, delete also some other objects:
- the users notifications
- the users triggers
- the workspaces (investigations and dashboards) for which the user is the only admin.
- the user background tasks, the background tasks the user is the only admin of

**Comment by SamuelHassine** [comment] 2023-08-10 17:12
@Archidoit duplicate of https://github.com/OpenCTI-Platform/opencti/issues/3720 ?

**Comment by Archidoit** [comment] 2023-08-11 07:26
Yes it is, I'm going to close this issue and add the user background tasks in the list of things to delete in #3720.

**Closed as not planned** 2023-08-11 07:26 UTC
Labels: duplicate, feature
