### ISSUE TITLE
CSV Export Missing Relationships

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#7979] opened 2024-08-07 12:41 UTC
## Description

When an admin user exports data for an SDO the data is only exported for 2 cells and the data is missing all relationships.

## Environment

1. OS : RHEL8
2. OpenCTI version: 6.2.7
3. OpenCTI client: frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Exports data for an SDO .
2. View the exported CSV and look for correlating relationships.

## Expected Output

Exported CSV SDO's show all correlated relationships.

## Actual Output

Missing correlated relationships.

## Additional information

None

**Comment by nino-filigran** [comment] 2024-08-08 07:15
@explorecti can you be a bit more specific about reproducing steps please?
- which type of entity are you trying to export?
- which export are you doing (simple/full)?
- from which screen are you launching the export? 
Thanks in advance

**Comment by nino-filigran** [comment] 2024-08-08 07:20
What I've noticed is that If I export CSV (full) from knowledge/data of an entity, the first neighbors are not exported (which is normal because the entity types do have different data models)

**Comment by explorecti** [comment] 2024-08-08 12:52
Will gather more information please do not close the ticket. There will be a delayed response, target date (08/13). Thank you!

**Comment by nino-filigran** [comment] 2024-09-11 12:15
@explorecti Did you manage to gather more info?

**Comment by nino-filigran** [comment] 2024-09-16 07:48
Closing the ticket since no feedback so far. Feel free to reopen if needs be!

**Closed as completed by nino-filigran** 2024-09-16 07:48 UTC
Labels: question, solved
