### ISSUE TITLE
Updating own opinion on cases displays an error (but is successful)

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#9086] opened 2024-11-19 15:32 UTC
## Description

Create a case, open it and from the details add an opinion.
Radar is updated.
You're now listed in the new (6.4.0) Opinion list dialog, when you click on the radar..

Try to add another opinion => Error

![Image](https://github.com/user-attachments/assets/957cc58e-8b44-4cc4-8e37-6f9854de3337)

Refresh page : opinion was successfully updated.

## Environment

OCTI 6.4.0

## Expected Output

No error, opinion updated in the UI.

**Comment by nino-filigran** [comment] 2024-11-25 08:46
@labo-flg I am not able to reproduce on public demo, therefore, closing this bug. However if you think I'm wrong, just let me know and I'll reopen it.

**Closed as completed by nino-filigran** 2024-11-25 08:46 UTC
Labels: bug, wontfix
