### ISSUE TITLE
CSV Mapper has a parsing issue with booleans in "False" state

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#5318] opened 2023-12-28 14:25 UTC
## Description

By assigning the boolean "False" to a value in a CSV I want to parse, the mapper doesn't detect any objects (entities or relations).

## Environment

OpenCTI version: 5.12.14

## Reproducible Steps

1. I want to create a CSV Mapper entitled 'Malware' with headers and semicolons. The malware entity has name in column A, is family in column B and malware types in C:

![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/9d1bfa3e-2d13-4530-b8a9-f5c2248558b0)

2. For example, I test a CSV file containing in column A: malware_name = test, column B: is_family = **False**, column C: malware_types = bot.

![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/5499a62d-c7b2-45c3-9df4-879bb7665e7d)

![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/0fa5d6d0-54d1-4845-aaad-f35592b36689)

## Expected Output

The test should return the parsing of the CSV in JSON format even if the is_family value is unknown and therefore with status 'False'.

## Actual Output

The mapper finds no objects and returns an empty page.

**Comment by lndrtrbn** [comment] 2023-12-29 08:15
Seems to be a duplicate of #5300

**Closed as completed** 2023-12-29 08:20 UTC
Labels: bug, duplicate
