### ISSUE TITLE
Missing organizations in user create/edit screen

### ISSUE THREAD

**Issue by dmmartin13** [LuatixHQ/opencti#2609] opened 2022-11-25 21:46 UTC
## Description

When adding a new user or editing an existing one, the list of organizations is incomplete. I created an organization for my Agency and it appears in the dropdown to set the platform organization, but not in the organization dropdown on the create/edit user screen. As a result, users cannot be assigned to an organization and non-administrative users receive an error message when logging in to the platform, saying "you can't log without an organization" (admins can still log in).

## Environment

1. OS (where OpenCTI server runs): Docker on Ubuntu 22.04 LTS
2. OpenCTI version: OpenCTI 5.4.0 
3. OpenCTI client: frontend
4. Other environment details: using external 3-node Elasticsearch cluster

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new organization
2. Select that organization from the "platform organization" dropdown on the configuration page
3. Attempt to set one or more users as members of the same organization from the add or edit users page

## Expected Output

The users should have the option to associate them with the same organization.

## Actual Output

The newly added organization is missing from the dropdown

## Additional information

There are 4.91k organizations in our platform.

**Comment by richard-julien** [comment] 2022-11-26 10:37
Hi @dmmartin13 , im not able to reproduce.
That I notice is we forget to order alphabeticaly the list in the user screen so its harder to find the organization.
Can you try to search inside the box by starting to write the first letter of the organization ?

**Comment by dmmartin13** [comment] 2022-11-28 11:24
I tried that and my organization doesn't appear in the list even when doing a search from the accesses->update a user screen. There are some visible difference between the two lists.

![Screenshot 2022-11-28 at 6 17 48 AM](https://user-images.githubusercontent.com/15142653/204265512-d295bc63-9686-4083-915e-7a48170fb0f6.png)
Unfiltered list on platform organization box
![Screenshot 2022-11-28 at 6 17 10 AM](https://user-images.githubusercontent.com/15142653/204265514-bad06873-4cf3-40f1-b117-c9abbdc558a1.png)
Filtered list on platform organization box
![Screenshot 2022-11-28 at 6 18 20 AM](https://user-images.githubusercontent.com/15142653/204265518-21f27970-1945-4f3c-8eff-3f5ad866f5e4.png)
Unfiltered organization list on edit user screen
![Screenshot 2022-11-28 at 6 18 32 AM](https://user-images.githubusercontent.com/15142653/204265517-e17a0e76-c441-4793-8c40-0aae02f4b1bf.png)
Filtered organization list on edit user screen

**Comment by SamuelHassine** [comment] 2022-12-02 18:04
Bug confirmed, missing the request to show more than 200 organizations. Will be fixed soon.

**Closed as completed** 2022-12-03 10:02 UTC
Labels: bug, solved
