### ISSUE TITLE
Using stixCyberObservables to get file observable data

### ISSUE THREAD

**Issue by annoyingapt** [LuatixHQ/opencti#6676] opened 2024-04-11 21:39 UTC
## Description

Currently I am unable to retrieve a file observable in graphql using stixCyberObservables using the value key (could be user error?). If I have the observable id, I can use that to complete the search. I assume the issue is that there is no value in the file observable field as it is broken up into MD5 SHA1 etc etc.

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: 6.0.9

## Reproducible Steps

Graphql query by value:
```
{
  stixCyberObservables(
    filters: {
      mode: and
      filters: [
        { key: "value", values: "aa8a9071e074b05a85b53f165792b649" }
      ]
      filterGroups: []
    }
  ) {
    edges {
      node {
        observable_value
      }
    }
  }
}
```

## Expected Output

Return the observable_value

## Actual Output

```
{
  "data": {
    "stixCyberObservables": {
      "edges": []
    }
  }
}
```

## Additional information

I can use the id if I have it, which works fine. But I don't always have this available.
```
{
  stixCyberObservables(
    filters: {
      mode: and
      filters: [
        { key: "id", values: "eb856d8a-b015-4464-a677-60a8a7f836a3" }
      ]
      filterGroups: []
    }
  ) {
    edges {
      node {
        observable_value
      }
    }
  }
}
```

## Screenshots
![query1](https://github.com/OpenCTI-Platform/opencti/assets/55898651/af7bc68b-d304-46da-a649-d4852206a594)
![query2](https://github.com/OpenCTI-Platform/opencti/assets/55898651/bba9f6e7-1ebf-475b-8fe9-3e20a6925cdf)

**Comment by nino-filigran** [comment] 2024-04-15 07:13
@annoyingapt after talking internally to the devs, it's seems that your query does not find any result since the field "key" does not exist for this observable, hence the fact that you're not finding any result.

**Comment by annoyingapt** [comment] 2024-04-15 07:21
Sorry I'm a bit confused by this response, should there be a key? Does it work for you?

**Comment by nino-filigran** [comment] 2024-04-15 07:51
My bad, my answer was far from from giving concrete details. 
So: 
1. your query fails because you're not looking for the right field in your query: the key that you're looking for incorrect.
2. If you're looking for a MD5, this is the correct key (I tested it and it works):
```
{
  stixCyberObservables(
    filters: {
      mode: and
      filters: [
        { key: "hashes.MD5", values: "valueofyourMD5" }
      ]
      filterGroups: []
    }
  ) {
    edges {
      node {
        observable_value
      }
```

IS that clearer and answers your question? Given I'm not able to reproduce, if you're able to successfuly find your result, would you mind closing this bug? If you still encounter issues, please let us know.

**Comment by annoyingapt** [comment] 2024-04-15 19:10
Right I see, I'll need to modify my code that makes the graphql queries. So It determines the length of the hash before making the query, so it knows which hash to use. Rather than using value for the key.

**Closed as completed** 2024-04-15 19:15 UTC
Labels: question, solved
