### ISSUE TITLE
Indicator list export error 

### ISSUE THREAD

**Issue by eddiestaffy08** [LuatixHQ/opencti#5870] opened 2024-02-09 01:40 UTC
## Description

When trying to export indicators from a report, the export stays as pending with the following error:

Connector ready to process the operation, {'name'}:'UnsupportedError','message': '[FILTER] invalid filer'}

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }: Debian 12.4
4. OpenCTI version: OpenCTI 5.12.9
5. OpenCTI client: frontend
6. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Analyses, reports, select any report. I chose "Spyware isn't going anywhere, and neither are its tactics".
2. Select entities
3. Add filter for indicators
4. individually select each indicator
5. Remove indicator filter but keep the indicators selected
6. Open the export panel and add a new export
7. Choose text/CSV, full export, marking: TLP: Clear

## Expected Output

CSV export ready to download

## Actual Output

Connector ready to process the operation, {'name'}:'UnsupportedError','message': '[FILTER] invalid filer'}

## Additional information

I was then able to generate an export for the indicators when I followed the steps from a previously resolved issue ( Error when export list #4889)

## Screenshots (optional)
![OpenCTI error](https://github.com/OpenCTI-Platform/opencti/assets/156980535/e193eafe-5179-4c52-8e4a-1ae37822d4f3)

**Comment by nino-filigran** [comment] 2024-02-09 08:30
@eddiestaffy08 I have several points here: 
- first, I cannot reproduce your bug, for me export works fine. 

Could you please try to upgrade to the most recent version? And let me know if the problem still happens?

Additionally, the ability to export only a subpart of a list within a container or a specific context is a **feature not implemented yet**. It's not ideal I know, therefore what you're trying to do is simply not possible for the moment. As a result you should at least be able to download the whole list of entities.

**Comment by SamuelHassine** [comment] 2024-02-09 09:53
Hello,

This was fixed in 5.12.29.

Kind regards,
Samuel

**Closed as completed by SamuelHassine** 2024-02-09 09:53 UTC
Labels: bug, duplicate, filters & search

**Comment by eddiestaffy08** [comment] 2024-02-12 01:01
Hi Guys, thanks for the replies! I will update to rectify the issue!
