### ISSUE TITLE
Account deletion error

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#5580] opened 2024-01-18 05:10 UTC
OpenCTI version: OpenCTI 5.12.20

When I tried to delete an unnecessary account, I received an error.

![de](https://github.com/OpenCTI-Platform/opencti/assets/19428462/00a038a0-518a-4920-b466-6b8641b09116)

Please check it out and let me know how to fix it.

Thanks :)

**Comment by Jipegien** [comment] 2024-01-18 08:31
@aHenryJard can you look into this?

**Comment by Jipegien** [comment] 2024-01-18 08:35
@misohouse I am not able to reproduce. Can you give us more details about the situation? The user is associated with dashboard or investigation? Have you access to error logs ?

**Comment by misohouse** [comment] 2024-01-19 00:01
@Jipegien This account had only performed data retrieval, such as reports, since creation. I got the same error on this account as well as other accounts.

The error log is below. 

`ERR Fail to execute engine pagination | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500,"query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":2,"should":[{"bool":{"minimum_should_match":3,"should":[{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["event_source_id.keyword"],"query":"be6b5136-4db9-4ccd-b2fa-cb8031387f27"}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["status.keyword"],"query":"complete"}}]}},{"bool":{"minimum_should_match":1,"should":[{"range":{"completed_time":{"lte":"now-7d/d"}}}]}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["entity_type.keyword","parent_types.keyword"],"query":"Work"}}]}}]}}],"must_not":[]}},"size":5000,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_history"],"track_total_hits":true}},"message":"Fail to execute engine pagination","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Fail to execute engine pagination\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:2483:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at elList (/opt/opencti/build/src/database/engine.js:2506:22)\n    at deleteCompletedWorks (/opt/opencti/build/src/manager/connectorManager.js:93:3)\n    at connectorHandler (/opt/opencti/build/src/manager/connectorManager.js:117:7)\n    at /opt/opencti/build/src/manager/connectorManager.js:137:9\n    at nht.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"},{"message":"The content length (536901428) is bigger than the maximum allowed string (536870888)","name":"RequestAbortedError","stack":"RequestAbortedError: The content length (536901428) is bigger than the maximum allowed string (536870888)\n    at ann.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:574:34)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at jYe.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:89:10)\n    at elList (/opt/opencti/build/src/database/engine.js:2506:22)\n    at deleteCompletedWorks (/opt/opencti/build/src/manager/connectorManager.js:93:3)\n    at connectorHandler (/opt/opencti/build/src/manager/connectorManager.js:117:7)\n    at /opt/opencti/build/src/manager/connectorManager.js:137:9\n    at nht.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"}] manager=CONNECTOR_MANAGER timestamp=2024-01-18T23:54:45.364Z version=5.12.20`

**Comment by aHenryJard** [comment] 2024-01-19 09:45
Hello @misohouse, the logs that you are sharing does not relate to account deletion, it's another issue for the connector manager that unfortunaly ran at the same time as background task. Do you have other error logs before this one ?

Reading your first description it seems to me that it's an account that was used for connector, do you know if the account was used only for connector or also for the web ui ? It could help us to narrow the issue.

I am not reproducing either so far.

**Comment by misohouse** [comment] 2024-01-21 23:38
@aHenryJard The account hasn't done anything since it was created.
![1231](https://github.com/OpenCTI-Platform/opencti/assets/19428462/0d1da27d-ba3e-4507-a864-e1e9ac5bdabd)

The figure below shows the connectors currently in use.
![123123](https://github.com/OpenCTI-Platform/opencti/assets/19428462/49294244-27b0-4e81-bad8-9ebe732ce87b)

The connectors shown in red are currently disabled due to heavy load.
(Commented by docker-compose)

I found another error message in opencti containers log.

This is the message that occurs just before the error message I showed above.
`1970/01/01 09:01AM ERR Platform unmanaged direct error | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot read properties of undefined (reading 'some')","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Cannot read properties of undefined (reading 'some')\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:70:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)\n    at Object.willSendResponse (/opt/opencti/build/src/graphql/loggerPlugin.js:115:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at b (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:530:5)\n    at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"},{"message":"Cannot read properties of undefined (reading 'some')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'some')\n    at isUserTheLastAdmin (/opt/opencti/build/src/domain/user.js:734:49)\n    at /opt/opencti/build/src/domain/user.js:746:34\n    at Array.filter (<anonymous>)\n    at deleteAllWorkspaceForUser (/opt/opencti/build/src/domain/user.js:746:6)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at userDelete (/opt/opencti/build/src/domain/user.js:831:3)"}] inner_relation_creation=0 operation=UserPopoverDeletionMutation operation_query=mutation UserPopoverDeletionMutation($id:ID!){userEdit(id:$id){delete}} size=45 timestamp=2024-01-21T23:41:38.518Z type=WRITE_ERROR user={"group_ids":["eee3b034-1ea2-4281-884c-337697819212"],"ip":"::ffff:192.168.200.162","organization_ids":[],"referer":"http://192.168.200.152:8080/dashboard/settings/accesses/users/6ff42a72-6fad-4fb7-a16e-fceffc716ac5","socket":"query","user_id":"74d07ecc-fd2c-47eb-b13c-f3ea7e6b2768"} variables={"id":"6ff42a72-6fad-4fb7-a16e-fceffc716ac5"} version=5.12.20`

**Comment by misohouse** [comment] 2024-01-21 23:59
@aHenryJard Unusually, it does not clear the work that currently exists in the CVE connector. (Could this be a problem?)
![1111](https://github.com/OpenCTI-Platform/opencti/assets/19428462/3a198445-c6eb-41b6-9f1e-3c6e04367a71)

`
ry":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"should":[{"bool":{"must_not":{"exists":{"field":"authorized_members"}}}},{"terms":{"authorized_members.id.keyword":["ALL","74d07ecc-fd2c-47eb-b13c-f3ea7e6b2768","eee3b034-1ea2-4281-884c-337697819212","739fe2d4-397c-4dca-9956-b074e33795d2"]}}]}},{"bool":{"minimum_should_match":1,"should":[{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["connector_id.keyword"],"query":"be6b5136-4db9-4ccd-b2fa-cb8031387f27"}}]}}]}}],"must_not":[]}},"size":500,"sort":[{"timestamp":{"missing":"_last","order":"desc"}},{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":"opencti_history*","track_total_hits":true}},"message":"Fail to execute engine pagination","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Fail to execute engine pagination\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:2483:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at deleteWorkForConnector (/opt/opencti/build/src/domain/work.js:126:15)"},{"message":"The content length (536931461) is bigger than the maximum allowed string (536870888)","name":"RequestAbortedError","stack":"RequestAbortedError: The content length (536931461) is bigger than the maximum allowed string (536870888)\n    at ann.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:574:34)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at jYe.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:89:10)\n    at deleteWorkForConnector (/opt/opencti/build/src/domain/work.js:126:15)"}],"inner_relation_creation":0,"level":"error","message":"Fail to execute engine pagination","operation":"ConnectorWorkDeleteMutation","operation_query":"mutation ConnectorWorkDeleteMutation($connectorId:String!){workDelete(connectorId:$connectorId)}","size":54,"time":3927,"timestamp":"2024-01-21T23:55:04.536Z","type":"WRITE_ERROR","user":{"group_ids":["eee3b034-1ea2-4281-884c-337697819212"],"ip":"::ffff:192.168.200.162","organization_ids":[],"referer":"http://192.168.200.152:8080/dashboard/data/connectors/be6b5136-4db9-4ccd-b2fa-cb8031387f27","socket":"query","user_id":"74d07ecc-fd2c-47eb-b13c-f3ea7e6b2768"},"variables":{"connectorId":"be6b5136-4db9-4ccd-b2fa-cb8031387f27"},"version":"5.12.20"}
`

And on a test opencti server that I am currently running separately, I have confirmed that the account is deleted normally.

**Comment by misohouse** [comment] 2024-01-22 00:49
@aHenryJard After a lot of testing, I think elasticsearch might be the problem. 

My previous version was 8.11.3, now it's 8.12.0, and when I rolled back to 8.11.3, I get an error when running elasticsearch.

The version of Elasticsearch on my test opencti server where account deletion works fine is 8.11.3.

Is it possible that the data stored in the 8.11.3 version was transformed when it was moved to the 8.12.0 version, causing the account deletion error?

**Comment by aHenryJard** [comment] 2024-01-26 13:55
Thanks you for that many details @misohouse 

So first the error log "Cannot read properties of undefined (reading 'some')\n    at isUserTheLastAdmin (/opt/opencti/build/src/domain/user.js:734:49)" is totally related to user deletion.

For versions, I read 8.12.0 but I think you are thinking on 5.12.0, if not please tell me.

For the rollback, have you done a backup of elastic data before moving to 5.12.0 ? Because you are right, a migration of data is done when a new version of OpenCTI is running for the first time after an upgrade, and there is no way back. In particular in the version 5.12.0 there is filter migration that is a change accros all application and many data format.

https://github.com/OpenCTI-Platform/opencti/releases/tag/5.12.0

So as far as I know, if you keep elastic data, you cannot go back from 5.12.0 to 5.11.3

I don't know why you had to rollback, but there has been a lot effort of bug fix lately, maybe you can try to use the latest version of OpenCTI ?

**Comment by aHenryJard** [comment] 2024-01-26 16:52
@misohouse sorry you can forget my previous comment, you are talking about elastic version, and not OpenCTI version. I'm going to look around the error that you have shared in the code.

**Comment by aHenryJard** [comment] 2024-01-30 10:45
I reproduced the error with a test, it can occurs with Workspace that does not have authorized_member field in database for some reason. I propose to continue deletion if it happens https://github.com/OpenCTI-Platform/opencti/compare/issue/5580. I'm not sure why a Workspace can be missing authorized_member data.

![image](https://github.com/OpenCTI-Platform/opencti/assets/3634942/32085dd9-9ed6-4647-8815-113df85507df)

**Comment by Jipegien** [comment] 2024-01-30 10:58
> I reproduced the error with a test, it can occurs with Workspace that does not have authorized_member field in database for some reason. I propose to continue deletion if it happens https://github.com/OpenCTI-Platform/opencti/compare/issue/5580. I'm not sure why a Workspace can be missing authorized_member data.
> 
> ![image](https://private-user-images.githubusercontent.com/3634942/300775509-32085dd9-9ed6-4647-8815-113df85507df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTI1NDYsIm5iZiI6MTcwNjYxMjI0NiwicGF0aCI6Ii8zNjM0OTQyLzMwMDc3NTUwOS0zMjA4NWRkOS05ZWQ2LTQ2NDctODgxNS0xMTNkZjg1NTA3ZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMTA1NzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWEzMjA4YTZiMzZjMmMzYmYyODQ1ZmI3OGIxYTIzNDUyODFiMjIyODBhZWU5ZTJhNjZhMTFjYzE1NDQ2ZWQ1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TeeFLiq8-0O1TyqudJvN3w3JFmrEpzGlO7PkirRFRRU)

I'm fine with this solution.

**Closed as completed** 2024-01-30 13:30 UTC
Labels: bug, solved
