### ISSUE TITLE
Stream broken 5.9.6?

### ISSUE THREAD

**Issue by b1nbash** [LuatixHQ/opencti#3994] opened 2023-08-07 12:01 UTC
## Description

I have two instances of openCTI 5.9.6 and want to stream data between these. I successfully create a stream on instance A, and I manage to create a synchronizer on instance B. But when I try starting the synchronizer nothing happens, and if I revisit the "Ingestion"-tab I get the common error message: `Error  An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.`

## Environment

1. Ubuntu 22.04
2. OpenCTI version: OpenCTI 5.9.6 (docker)
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create stream
2. Create synchronizer
3. (Try) starting the synchronizer
4. Revisit "Ingestion"-tab

## Expected Output

Stream should be started

## Actual Output

`Error  An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.`

## Additional information

I have tested the same procedure with the instance ingesting the stream running openCTI 5.9.0, and **this works** as expected.

I know also that the stream is working correctly because I get expected results when curling `http://opencti/stream/live`

**Comment by SouadHadjiat** [comment] 2023-08-08 07:36
Closing as duplicate of https://github.com/OpenCTI-Platform/opencti/issues/3884

**Closed as not planned by SouadHadjiat** 2023-08-08 07:36 UTC
Labels: bug, duplicate
