### ISSUE TITLE
Refactor and rename all capabilities available in roles and add a description to display in the UI

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3757] opened 2023-07-13 09:09 UTC
## Use case

Refactor and rename all capabilities available in roles and add a description to display in the UI

**Comment by Jipegien** [comment] 2023-09-07 13:42
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2121

**Closed as not planned by Jipegien** 2023-09-07 13:42 UTC
Labels: duplicate, feature
