### ISSUE TITLE
Create a Web Service to consume the Connector for SaaS users 

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#6730] opened 2024-04-17 11:51 UTC
Goal is to have a webservice to access to the connector to be delivered to SaaS users.

**Comment by nino-filigran** [comment] 2024-09-25 08:28
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/5652

**Closed as completed by nino-filigran** 2024-09-25 08:28 UTC
Labels: duplicate, feature, enterprise edition
