### ISSUE TITLE
Distribution of relations take restricted entities into account

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3319] opened 2023-05-11 08:43 UTC
## Description

In the Knowledge of the entities, in 'distribution of relations', the relations with restricted entities are indicated.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

- In an admin session, create a relationship from X to Y, with Y an entity (ex: a threat actor) with marking=red.
- Log in another session (private window) with a user that has no access to red markings.
- Go to the knowledge tab of the X entity.
- In 'Distribution of relations', the entity type of Y is displayed (exemple: threat actor). But if we go to Knowledge>Threat actors, there is no relations.

## Expected Output
If a relationship exists to a restricted entity, its entity type should'nt be taken into account in the 'Distribution of relations' of the source entity knowledge tab.

## Screenshots (optional)
- a relationship with a threat actor is indicated:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/a9f5f45c-0614-4320-97ed-2f0f0728f627)
- but there is no relations displayed in Bretagne>Knowledge>Threat Actor (because the threat actor is not accessible for the user):
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/ee690ac5-24ae-4ad3-ac45-575dd373802a)

**Comment by Kedae** [comment] 2023-05-12 09:55
Need a brainstorm about that following a discussion with @RomuDeuxfois @Archidoit @Kedae @Jipegien

**Comment by Jipegien** [comment] 2023-05-12 15:13
Brainstorm output --> has to be treated as a bug to be resolved with low priority.

**Comment by richard-julien** [comment] 2023-05-16 09:18
As it by design, closing as wont fix.

**Closed as completed by richard-julien** 2023-05-16 09:18 UTC
Labels: wontfix, feature
