### ISSUE TITLE
[Export] Incomplete JSON export of reports

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7120] opened 2024-05-24 19:02 UTC
## Description

When exporting a report from the reports, if it contains many entities and relations, some of them are not included in the generated bundle (most of the relations are missing).

Maybe this issue hasn't been fully fixed : https://github.com/OpenCTI-Platform/opencti/issues/6499

## Environment

OCTI 6.1.4 (demo)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report
2. Include around 50 entities and 20 relations
3. Go to the Data tab
4. Generate an export (JSON, full export, no marking, no restriction)
5. Download the generated JSON
-> missing entities

## Expected Output

The bundle contains all entities and relations

## Actual Output

Many objects are missing (mostly relations)

## Additional information

Here is the report I used to reproduce: https://demo.octi.filigran.io/dashboard/analyses/reports/9cf75d3e-2f80-45eb-a18d-fb5d2129be5c/files

You can check what is inside my report, and what is in my export (0 relations in my export)

**Comment by nino-filigran** [comment] 2024-05-27 07:31
I have all the entities in object REF though. But Do not see any relations.

**Comment by Lhorus6** [comment] 2024-05-27 07:41
In my example yes, but it depends. Sometimes there are relationships but not all.

**Comment by SamuelHassine** [comment] 2024-05-31 10:40
Duplicate of https://github.com/OpenCTI-Platform/client-python/issues/669.

**Closed as completed by SamuelHassine** 2024-05-31 10:40 UTC
Labels: bug, duplicate
