### ISSUE TITLE
[CSV mapper] Can't import File Observable

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5933] opened 2024-02-12 11:02 UTC
## Description

When I try to import a hash as an observable with CSV mappers, an error occurs (see screenshot).

## Environment

OCTI 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a CSV mapper with only File representation (see conf in screenshot)
2. Create a csv file with one hash only
3. Import it with the newly created mapper

## Additional information

In the test output, we can see that the hash is put in a "hashes" json field (i.e. "hashes": "<my_hash>"). Usually, hashes are categorized like this :

"hashes":{
    "SHA-1": "<my_hash>"
}

Maybe that's where the problem lies.

### Error

![Screenshot 2024-02-12 110142](https://github.com/OpenCTI-Platform/opencti/assets/70956706/5a9fd769-3eb9-4534-93af-596c2c3020a4)

### CSV mapper config

![Screenshot 2024-02-12 115703](https://github.com/OpenCTI-Platform/opencti/assets/70956706/093b550b-34ba-48e5-8fd3-16cbea67c143)

### Test output

![Screenshot 2024-02-12 120108](https://github.com/OpenCTI-Platform/opencti/assets/70956706/4bc94d4b-3f5b-48b0-8485-c0147bf69bc9)

**Comment by Jipegien** [comment] 2024-02-12 14:22
duplicate of this : https://github.com/OpenCTI-Platform/opencti/issues/4806 will be handled in the next major.

**Closed as not planned by Jipegien** 2024-02-12 14:22 UTC
Labels: bug, duplicate
