### ISSUE TITLE
Why are all the observables in the graph the same color?

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#7546] opened 2024-07-01 00:32 UTC
OpenCTI Version : 6.2.0

All observables like IP, Domain Name, URL, etc. had different colors and were easy to see, but after applying the latest version, they are all light blue and hard to distinguish.
.
.
[Before]
![11](https://github.com/OpenCTI-Platform/opencti/assets/19428462/1b455a8a-a370-480c-871e-bcd5130bb3b6)
.
.
[After] It's hard to distinguish between observable data.
![22](https://github.com/OpenCTI-Platform/opencti/assets/19428462/b6175857-288c-4328-ba9d-4adf736195da)
.
.
Is there any way to make it look like the old way?
(The version I was using before was 6.1.8)

**Comment by misje** [comment] 2024-07-01 05:17
Same as #7538.

**Comment by Jipegien** [comment] 2024-07-01 09:14
considered as duplicate of #7538

**Closed as completed by Jipegien** 2024-07-01 09:14 UTC
Labels: bug, duplicate
