### ISSUE TITLE
Infrastructure Breaking Investigations

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#6801] opened 2024-04-24 12:24 UTC
## Description

When selecting infrastructure(add only) from a created or existing investigation all targets are shown/expanded.

## Environment

1. OS: Ubuntu
2. OpenCTI version: 6.0.10
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new investigation
2. Add entities and select TYPE: INFRASTRUCTURE
3. Select and click to expand
4. Under "All types of target" select Infrastructure 
5. click EXPAND
6. Results show ALL

## Expected Output

Should only return Infrastructure target

## Actual Output

Returns all targets

## Additional information

None

## Screenshots (optional)

None

**Comment by Jipegien** [comment] 2024-04-25 07:15
Can't reproduce it.
MalwareA targeting multiple entities. MalwareA targeting Infra1. Creating investigation that contains MalwareA. Expand -> Infrastructure. Only Infra1 appears.
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/ac4803c7-f7e3-4594-a941-e99b23f0999d)

Do you have any additional information about your situation?

**Comment by explorecti** [comment] 2024-04-25 10:50
@Jipegien Please select Type "Infrastructure" when adding entities then expand just the "All types of targets" and choose "Infrastructure", then it displays all targets. Don't use Malware as the example because that doesn't expose the issue.

**Comment by nino-filigran** [comment] 2024-04-25 12:30
@explorecti I confirm, I've been able to reproduce, by first adding the entity type = infra in the graph, then choosing to expand only infra, resulting in having not only infrastructures but all other linked entities added to my graph.

**Comment by explorecti** [comment] 2024-05-22 19:27
Is there an update when this will be fixed?

**Comment by nino-filigran** [comment] 2024-05-23 07:03
Hi @explorecti as you can see @SarahBocognano assigned herself on the ticket. Before, nobody did work on this. Therefore, this will be fixed soon. The ticket will be updated once done.

**Comment by SarahBocognano** [comment] 2024-05-29 09:23
Update: This issue is applicable to all entities, example :

- I add a threat Actor in investigation
- I select this threat actor 
- I select "Threat Actor" to expand only
Result : Every other relationships of this entity if expanded too

**Closed as completed** 2024-06-11 13:29 UTC
Labels: bug, solved, graph
