### ISSUE TITLE
Custom Workflow stages

### ISSUE THREAD

**Issue by rabbipigeon** [LuatixHQ/opencti#1979] opened 2022-03-23 07:52 UTC
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Does opencti Support custom workflows?

For example:

Default Report Workflow:
             New -> In progress -> Analyzed -> Closed

I would like to add
         Custom Report Workflow:
             New -> In progress -> Process part 1 -> process Part 2-> Analyzed -> Closed

## Environment

1. OS (where OpenCTI server runs): linux
2. OpenCTI version: 5.1.4

**Comment by SamuelHassine** [comment] 2022-03-23 07:54
Hello @rabbipigeon,

It's in our roadmap, duplicate of #1943.

**Closed as completed by SamuelHassine** 2022-03-23 07:54 UTC
Labels: duplicate, feature
