### ISSUE TITLE
LDAP issues with manual build

### ISSUE THREAD

**Issue by smclinden** [LuatixHQ/opencti#2282] opened 2022-08-15 16:59 UTC
## Description

I can login to tocal admin account via the Web but not into any LDAP accounts. I have tested the LDAP server and credentials are correct. Further, I had no problems with the same configuration on versions.

This seems to have been repeated, elsewhere, but I haven't found a fix.

## Environment

1. Ubuntu 18.04
2. OpenCTI 5.3.7
3. OpenCTI client: Web
4. Node 16.16.0

```
  "providers": {
    "ldap": {
	"strategy": "LdapStrategy",
        "config": {
	  "url": "ldap://ldap.org.com:389",
	  "bind_dn": "cn=srv-account,ou=Service Accounts,ou=EnterpriseGroups,dc=org,dc=com",
	  "bind_credentials": “*********”,
	  "search_base": "dc=org,dc=com",
	  "search_filter": "(&(objectCategory=Person)(sAMAccountName={{username}})(memberOf=CN=ITSecurity-OPS,OU=AutoManagedGroups,OU=EnterpriseGroups,DC=org,DC=org))”,
	  "account_attribute": "name",
          "mail_attribute": "userPrincipalName"    
	}
    },
    "local": {
      "strategy": "LocalStrategy"
    }
  }
```

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Build manually
2. Start OpenCTI
3. I can login via the Web using the local strategy but 

## Actual Output

```
Here is the error message that I am seeing. I have manually identified the LDAP credentials and user credentials are correct.

{"category":"APP","error":{"context":{"category":"technical","http_status":401},"message":"Wrong name or password","name":"AuthFailure","stack":"AuthFailure: Wrong name \
or password\n    at error (/apps/usr/local/src/opencti/build/src/config/errors.js:8:10)\n    at AuthenticationFailure (/apps/usr/local/src/opencti/build/src/config/error\
s.js:12:56)\n    at login (/apps/usr/local/src/opencti/build/src/domain/user.js:515:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:inter\
nal/process/task_queues:96:5)"},"level":"warn","message":"[AUTH] local","timestamp":"2022-08-15T13:43:18.746Z","version":"5.3.7"}
{"auth":{"email":"user@org.com","ip":"172.20.64.58","referer":"https://opencti.org.com:4000/dashboard"},"category":"AUDIT","level":"error","message":"LOGIN","\
resource":{"provider":"local"},"timestamp":"2022-08-15T13:43:18.747Z","version":"5.3.7"}
{"category":"APP","error":null,"info":{"message":"Invalid username/password"},"level":"warn","message":"[AUTH] ldapauth","timestamp":"2022-08-15T13:43:18.977Z","version"\
:"5.3.7"}
{"auth":{"email":"user@org.com","ip":"172.20.64.58","referer":"https://opencti.org.com:4000/dashboard"},"category":"AUDIT","level":"error","message":"LOGIN","\
resource":{"provider":"ldapauth"},"timestamp":"2022-08-15T13:43:18.977Z","version":"5.3.7"}
{"category":"APP","error":{"data":{"category":"technical","http_status":401},"stacktrace":["AuthFailure: Wrong name or password","at error (/apps/usr/local/src/opencti/b\
uild/src/config/errors.js:8:10)","at AuthenticationFailure (/apps/usr/local/src/opencti/build/src/config/errors.js:12:56)","at Object.token (/apps/usr/local/src/opencti/\
build/src/resolvers/user.js:117:13)","at runMicrotasks (<anonymous>)","at processTicksAndRejections (node:internal/process/task_queues:96:5)"]},"inner_relation_creation"\
:0,"level":"warn","message":"API Call","operation":"LoginFormMutation","operation_query":"mutation LoginFormMutation($input:UserLoginInput!){token(input:$input)}","size"\
:72,"time":1151,"timestamp":"2022-08-15T13:43:18.979Z","type":"WRITE_ERROR","version":"5.3.7"}
```

**Comment by smclinden** [comment] 2022-08-16 14:52
I tried clearning node_modules and doing a "yarn install" and got the following:

```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @endemolshinegroup/cosmiconfig-typescript-loader@npm:3.0.2 [62c2d] doesn't provide typescript (pffd2f), requested by ts-node
➤ YN0002: │ eslint-config-airbnb-typescript@npm:16.1.0 [5bd70] doesn't provide eslint (pd45ba), requested by eslint-config-airbnb-base
➤ YN0002: │ eslint-config-airbnb-typescript@npm:16.1.0 [5bd70] doesn't provide eslint-plugin-import (p4f1ea), requested by eslint-config-airbnb-base
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (p60135) with version 16.3.0, which doesn't satisfy what @graphql-codegen/typescript-resolvers and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (pe160b) with version 16.3.0, which doesn't satisfy what apollo-server-core and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (p2ae4a) with version 16.3.0, which doesn't satisfy what graphql-constraint-directive and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (pebcd9) with version 16.3.0, which doesn't satisfy what graphql-import and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (p2c3b2) with version 16.3.0, which doesn't satisfy what merge-graphql-schemas and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides prom-client (p400c7) with version 14.0.1, which doesn't satisfy what express-prometheus-middleware and some of its descendants request
➤ YN0002: │ opencti-graphql@workspace:. doesn't provide webpack (pf324c), requested by ts-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 340ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.4.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable-ts@npm:0.8.21 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 42s 894ms
➤ YN0000: ┌ Link step
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-android-arm64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-darwin-64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-darwin-arm64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-freebsd-64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-freebsd-arm64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-32@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-mips64le@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-ppc64le@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-riscv64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-s390x@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-netbsd-64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-openbsd-64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-sunos-64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-32@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-arm64@npm:0.14.23 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0007: │ esbuild@npm:0.14.23 must be built because it never has been before or the last one failed
➤ YN0007: │ @apollo/protobufjs@npm:1.2.2 must be built because it never has been before or the last one failed
➤ YN0007: │ gc-stats@npm:1.4.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.21.1 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.59 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 18s 513ms
➤ YN0000: Done with warnings in 1m 3s
```

**Comment by smclinden** [comment] 2022-08-17 17:24
```
{"category":"APP","error":{"data":{"category":"technical","http_status":401},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (/apps/usr/local/sr
c/opencti/build/src/config/errors.js:8:10)","at AuthRequired (/apps/usr/local/src/opencti/build/src/config/errors.js:20:39)","at i.resolve (/apps/usr/local/src/opencti/bu
ild/src/graphql/authDirective.js:34:23)","at t.resolve (/apps/usr/local/src/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/utils/sch
emaInstrumentation.ts:106:18)","at executeField (/apps/usr/local/src/opencti/build/node_modules/graphql/execution/execute.js:481:20)","at executeFields (/apps/usr/local/s
rc/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at executeOperation (/apps/usr/local/src/opencti/build/node_modules/graphql/execution/execute.js:344:
14)","at execute (/apps/usr/local/src/opencti/build/node_modules/graphql/execution/execute.js:136:20)","at b (/apps/usr/local/src/opencti/build/node_modules/apollo-server
-express/node_modules/apollo-server-core/src/requestPipeline.ts:500:20)","at processGraphQLRequest (/apps/usr/local/src/opencti/build/node_modules/apollo-server-express/n
ode_modules/apollo-server-core/src/requestPipeline.ts:406:28)","at runMicrotasks (<anonymous>)","at processTicksAndRejections (node:internal/process/task_queues:96:5)","a
t processHTTPRequest (/apps/usr/local/src/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/runHttpQuery.ts:433:24)"]},"inner_relation_
creation":0,"level":"warn","message":"API Call","operation":"RootPrivateQuery","operation_query":"query RootPrivateQuery{me{id name lastname language theme user_email cap
abilities{name id}}settings{platform_map_tile_server_dark platform_map_tile_server_light platform_hidden_types platform_feature_flags{id enable}platform_modules{id enable
}...AppThemeProvider_settings ...AppIntlProvider_settings id}about{version}}fragment AppIntlProvider_settings on Settings{platform_language}fragment AppThemeProvider_sett
ings on Settings{platform_title platform_favicon platform_theme platform_theme_dark_background platform_theme_dark_paper platform_theme_dark_nav platform_theme_dark_prima
ry platform_theme_dark_secondary platform_theme_dark_accent platform_theme_dark_logo platform_theme_light_background platform_theme_light_paper platform_theme_light_nav p
latform_theme_light_primary platform_theme_light_secondary platform_theme_light_accent platform_theme_light_logo}","size":2,"time":846,"timestamp":"2022-08-17T17:22:19.32
4Z","type":"READ_ERROR","version":"5.3.7"}
```

**Comment by richard-julien** [comment] 2022-08-22 17:27
Just tested with our own LDAP and im not able to reproduce.
Sample of our configuration.

```
    "ldap": {
      "strategy": "LdapStrategy",
      "config": {
        "url": "ldap://XXXXXXXXX:390",
        "bind_dn": "CN=Julien Richard,CN=Users,DC=fr",
        "bind_credentials": "XXXXXXXXXXXX",
        "search_base": "CN=Users,DC=fr",
        "search_filter": "(cn={{username}})",
        "mail_attribute": "userPrincipalName"
      }
    }
```

Not sure what i can do to identify your problem.

Any change you can share your LDAP with me to try to reproduce?

**Comment by richard-julien** [comment] 2022-08-24 20:03
Any news @smclinden ?

**Comment by richard-julien** [comment] 2022-08-28 22:36
Closing for now, please retry and reopen if needed,

**Closed as completed by richard-julien** 2022-08-28 22:36 UTC
Labels: question, solved
