### ISSUE TITLE
Can’t modify description field of entities

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#1612] opened 2021-10-02 08:32 UTC
## Description

I can create, but not modify the description field of entities.

## Environment

1. OS (where OpenCTI server runs): Mac OS Big Sur last version
2. OpenCTI version: 5.0.1
3. OpenCTI client: front-end UI
4. Other environment details: Safari last version

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Fill the description field of a new entity.
2. Modify the description field.
3. 

## Expected Output

The modified description of the entity.

## Actual Output

No changes in the description field.
 
## Screenshots (optional)

**Comment by SamuelHassine** [comment] 2021-10-02 12:02
Hello @JeromeSRT,

I'm not able to reproduce on our side. Can you be more specific? Type of entity? Able to reproduce in the demo? What do you see in the network console when updating the field? Is the description field the only one to be impacted?

Thanks.

Kind regards,
Samuel

**Comment by JeromeSRT** [comment] 2021-10-02 13:17
> Hello @JeromeSRT,
> 
> 
> 
> I'm not able to reproduce on our side. Can you be more specific? Type of entity? Able to reproduce in the demo? What do you see in the network console when updating the field? Is the description field the only one to be impacted?
> 
> 
> 
> Thanks.
> 
> 
> 
> Kind regards,
> 
> Samuel

Hello @SamuelHassine,

I can't modify the description of all entities, even with the admin account. I have no access account to the demo platform of OpenCTI.
Where is the network console ?
My OpenCTI is stand alone.

Kind regards,

Jérôme

**Comment by JeromeSRT** [comment] 2021-10-02 13:45
> Hello @JeromeSRT,
> 
> I'm not able to reproduce on our side. Can you be more specific? Type of entity? Able to reproduce in the demo? What do you see in the network console when updating the field? Is the description field the only one to be impacted?
> 
> Thanks.
> 
> Kind regards, Samuel

Hello @SamuelHassine 

I have this error message at the user connexion:

{"type":"READ_ERROR","operation_query":"query RootPrivateQuery{me{id name lastname language theme user_email capabilities{name id}}settings{platform_map_tile_server_dark platform_map_tile_server_light ...AppThemeProvider_settings ...AppIntlProvider_settings id}}fragment AppIntlProvider_settings on Settings{platform_language}fragment AppThemeProvider_settings on Settings{platform_theme platform_theme_dark_primary platform_theme_dark_secondary platform_theme_dark_logo platform_theme_light_primary platform_theme_light_secondary platform_theme_light_logo}","inner_relation_creation":0,"operation":"RootPrivateQuery","time":47,"size":2,"error":{"data":{"http_status":401,"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (/Users/Jerome/Applications/OpenCTI/opencti/build/src/config/errors.js:8:10)","at AuthRequired (/Users/Jerome/Applications/OpenCTI/opencti/build/src/config/errors.js:22:3)","at AuthDirective.authenticationControl (/Users/Jerome/Applications/OpenCTI/opencti/build/src/graphql/authDirective.js:37:22)","at field.resolve (/Users/Jerome/Applications/OpenCTI/opencti/build/src/graphql/authDirective.js:78:19)","at field.resolve (/Users/Jerome/Applications/OpenCTI/opencti/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)","at resolveField (/Users/Jerome/Applications/OpenCTI/opencti/node_modules/graphql/execution/execute.js:464:18)","at executeFields (/Users/Jerome/Applications/OpenCTI/opencti/node_modules/graphql/execution/execute.js:292:18)","at executeOperation (/Users/Jerome/Applications/OpenCTI/opencti/node_modules/graphql/execution/execute.js:236:122)","at executeImpl (/Users/Jerome/Applications/OpenCTI/opencti/node_modules/graphql/execution/execute.js:116:14)","at Object.execute (/Users/Jerome/Applications/OpenCTI/opencti/node_modules/graphql/execution/execute.js:60:35)","at /Users/Jerome/Applications/OpenCTI/opencti/node_modules/apollo-server-core/src/requestPipeline.ts:571:22","at Generator.next (<anonymous>)","at /Users/Jerome/Applications/OpenCTI/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","at new Promise (<anonymous>)"]},"category":"APP","version":"5.0.1","level":"warn","message":"API Call","timestamp":"2021-10-02T13:40:48.192Z"}

Regards, Jerome

**Comment by SamuelHassine** [comment] 2021-10-02 21:27
Thanks @JeromeSRT, I'am able to reproduce. This will be fixed in the next release.

**Closed as completed** 2021-10-03 14:47 UTC
Labels: bug, solved
