### ISSUE TITLE
[Investigation] Impossible to add an entity to an investigation

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5559] opened 2024-01-17 17:33 UTC
## Description

When I try to add an entity to an organization by clicking on the blue "+" in the bottom right-hand corner, I can't because the search doesn't work. When I click on the search bar, nothing happens, I can never write inside.

## Environment

OCTI 5.15.19 (filigran and demo)
Firefox 121.0.1 (64-bit)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an investigation
2. Click on the blue "+" in the bottom right-hand corner
3. Try to search something -> you can't write inside the search bar

## Screenshots 

![Screenshot 2024-01-17 182931](https://github.com/OpenCTI-Platform/opencti/assets/70956706/992cbddc-00ac-4bc5-864a-16f65f5e4da7)

**Comment by Lhorus6** [comment] 2024-01-17 17:59
This issue could be linked to the issue : 
- https://github.com/OpenCTI-Platform/opencti/issues/5558
- https://github.com/OpenCTI-Platform/opencti/issues/5563

**Comment by Jipegien** [comment] 2024-01-17 18:14
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/5563

**Closed as completed by Jipegien** 2024-01-17 18:14 UTC
Labels: bug, duplicate
