### ISSUE TITLE
When creating a relationship within a shared report, Cannot read properties of undefined (reading 'internal_id') 

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#7846] opened 2024-07-29 12:42 UTC
## Description

As a user from an organization with which a report has been shared, I get an error when creating a relationship between two entities within the report

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Share a report with an organization
2. Log in with a user from this organization (user is not super admin in my case)
3. Add two entities to the report
4. Create a relationship between both

## Expected Output

No error

## Actual Output

Cannot read properties of undefined (reading 'internal_id')

## Additional information

If we try to create the relationship again, then we have this error: **Restricted relation already exists**

**Comment by SamuelHassine** [comment] 2024-07-29 12:57
It seems the relationship is not correctly shared at creation with all the organizations of the current user.

**Comment by romain-filigran** [comment] 2024-07-29 15:05
@yassine-ouaamou @SamuelHassine Not able to reproduce with the current “rolling” version. Is there any chance that this has been fixed in the meantime?

**Comment by yassine-ouaamou** [comment] 2024-07-29 15:30
Reproduced in testing. I will send you more data to reproduce

**Comment by romain-filigran** [comment] 2024-07-30 07:06
Ok reproduced on testing

**Closed as completed** 2024-07-30 14:50 UTC
Labels: bug, solved, critical
