### ISSUE TITLE
[UI Regression] Objects' description is always truncated and cannot be expanded

### ISSUE THREAD

**Issue by MalwareCantFly** [LuatixHQ/opencti#5693] opened 2024-01-25 16:35 UTC
## Description

Hi,
There appears to be a UI regression, which is also present in the latest release 5.12.21:

There used to be a small arrow button to expand and see the full description of an object (like the description of an Intrusion-Set).
Now, the description is truncated, and there is no option to see the full description.
A user would have to guess, and click on the Edit button, to see the full description.

It would be great, if this could be reverted.
Thanks!

## Environment

5.12.21

## Reproducible Steps

1. Create a new Intrusion-Set
2. Write a long description
3. Save, and the description will appear truncated.

## Screenshot of current state
<img width="460" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/33734448/ed5a173d-41d0-412d-9aa7-0ab41a96c768">

**Comment by SamuelHassine** [comment] 2024-01-26 07:52
Duplicate of #5682.

**Closed as completed by SamuelHassine** 2024-01-26 07:52 UTC
Labels: bug, duplicate
